
header=Ac No,Disb date,Disb Amt,Maturity date,Principal Repaid,Interest Repaid,OD DAYS,RPA,Total Misc Char due,Late charge Due,\
 Late charge ,Ledger Balance,Adjusted balance for accrual Calculation,Current Principal,Total Int due,Ac status,Ac closed date,Last payment date,\
 Accrued Interest,Orginal No of payments,Payment satisfied,Tag,URN,Date of first payment,Interest Rate,Payment current amount,\
 Tenure,Frequency,Schedulde Payment Next ,Net Payoff Amt,Uncollected Principal (Computed),Uncollected Interest (Computed),Scheduled Payment Number,\
 AccountName,ProductType,ProductCode,BranchCode,BranchName,PenalInterestRate,GlSubhead,OpenedOnValueDate,NextDemandRunDate,LastDemandRunDate,LastBookingDate,\
 LastArchiveDate,NumAdvanceSatisfiedDemands,BookedNotDuePenalInterest,BookedNormalInterest,BookedPenalInterest,TotalDisbursedAmount,TotalRepaidAmount,\
 TotalPenalInterestRepaid,TotalDemandDue,Total Fee Paid,Gurantor Customer Id,Phone No.,Open UserId,Fee1 Category,Fee1 Amount,Fee1 Gross Amount,Fee1 Payment Status,\
 Fee2 Category,Fee2 Amount,Fee2 Gross Amount,Fee2 Payment Status,Fee3 Category,Fee3 Amount,Fee3 Gross Amount,Fee3 Payment Status,Fee4 Category,Fee4 Amount,\
 Fee4 Gross Amount,Fee4 Payment Status,Fee5 Category,Fee5 Amount,Fee5 Gross Amount,Fee5 Payment Status,Customer name,Guarantor Name,Guarantor Ph no,\
 Customer BranchName,Asset Category,Provisioned Amount,Customer Type,Vertical,Document Type,Document Num,Primary Value Chain,Secondary Value Chain,Intervention,Hypothecated to,\
 Loan Sourcing Details,K2BName/Referral Name,K2BCode/Referral Code,Samunnati Pay card,Collateral,Address 1,Address 2,Address 3,City,State,Pin Code,Phone No,Email Id,GSTIN,RO Name,Moratorium Interest,Moratorium Tenure,MoratoriumPayOffAmount,NormalInterestSuspense,PenalInterestSuspense,Collateral Value,SBU,Current RM,Product Solutions,Customer UMRN,Guarantor UMRN,Subproduct


query= select w.account_id,w.first_disbursement_date,lp.amount_magnitude,w.maturity_date, \
w.total_principal_repaid_magnitude,w.total_normal_interest_repaid_magnitude,  \
case when w.oldest_due_demand_num = 0 then 0 else datediff(bk.current_working_date, d.demand_date) end as dpd, \
'' as rpa,w.total_fee_due_magnitude,w.total_penal_interest_due_magnitude,'' as \
lateChargeAsseseedLife,b.balance_magnitude,b.balance_magnitude as bal, \
w.total_principal_due_magnitude,w.total_normal_interest_due_magnitude,p.operational_status, \
p.closed_on_value_date as closed_on_value_date, w.last_repayment_date, \
w.booked_not_due_normal_interest_magnitude,w.num_demands,w.num_satisfied_demands,lt.tag as \
oldAccNo,ah.customer_id,w.first_repayment_date,lp.normal_interest_rate, \
w.installment_amount_magnitude as amount_magnitudes, \
case when \
lp.tenure_unit=1 then lp.tenure_days when lp.tenure_unit=2 then ROUND(lp.tenure_days/7) when \
lp.tenure_unit=3 then ROUND(lp.tenure_days/14) when lp.tenure_unit=4 then lp.tenure_months \
when lp.tenure_unit=5 then ROUND(lp.tenure_months/3) when lp.tenure_unit=6 then ROUND(lp.tenure_months/6) \
when lp.tenure_unit=7 then ROUND(lp.tenure_months/12) end as tenure, \
case when lp.tenure_unit=1 \
then 'DAY' when lp.tenure_unit=2 then 'WEEK' when lp.tenure_unit=3 then 'FORTNIGHT' when \
lp.tenure_unit=4 then 'MONTH' when lp.tenure_unit=5 then 'QUARTER' when lp.tenure_unit=6 \
then 'HALF_YEAR' when lp.tenure_unit=7 then 'YEAR' end as time_unit, \
w.next_demand_scheduled_date,(abs(b.balance_magnitude)+w.total_normal_interest_due_magnitude+w.total_penal_interest_due_magnitude+ \
w.booked_not_due_penal_interest_magnitude+w.booked_not_due_normal_interest_magnitude+w.total_fee_due_magnitude) as NetPayoffDue, \
'' as uncollectedPrincipal,'' as uncollectedInterest, '' as scheduledPaymentNumber,p.account_name,p.product_type, \
p.product_code,p.branch_code,bc.branch_name, lp.penal_interest_rate,p.gl_subhead,p.opened_on_value_date, \
w.next_demand_run_date,w.last_demand_run_date,w.last_booking_date,b.last_archive_date, \
w.num_advance_satisfied_demands,w.booked_not_due_penal_interest_magnitude, \
w.booked_normal_interest_magnitude,w.booked_penal_interest_magnitude, \
w.total_disbursed_magnitude,w.total_repaid_magnitude,w.total_penal_interest_repaid_magnitude, \
w.total_demand_due_magnitude,w.total_fee_repaid_magnitude,lp.guarantor_customer_id1, ah.phone1,p.open_user_id, \
fee1_category, fee1_amount,fee1_gross_amount, fee1_payment_status,fee2_category, fee2_amount,fee2_gross_amount, fee2_payment_status, \
fee3_category, fee3_amount,fee3_gross_amount, fee3_payment_status,fee4_category, fee4_amount,fee4_gross_amount, fee4_payment_status, \
fee5_category, fee5_amount,fee5_gross_amount, fee5_payment_status,\
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')) as customerName, \
concat(COALESCE(c.first_name,''),(case when COALESCE(c.middle_name,'')='' then '' else (concat(' ',COALESCE(c.middle_name,''))) end),' ',COALESCE(c.last_name,'')) as guarantorName, \
c.phone1 as guarantorPhone1, bcs.branch_name as customerBranchName, w.asset_category, w.total_provisioned_amount_magnitude as provisionedAmount, case when \
cs.customer_type=0 then 'Individual' when cs.customer_type=1 then 'Organisation' when cs.customer_type=2 then 'Public Limited'  \
when cs.customer_type=3 then 'Private Limited' when cs.customer_type=4 then 'Partnership' when cs.customer_type=5 then 'Society'  \
when cs.customer_type=6 then 'Trust' when cs.customer_type=7 then 'Government'  when cs.customer_type=8 then 'HUF'  \
when cs.customer_type=9 then 'FII' when cs.customer_type=10 then 'AOPBOI' when cs.customer_type=11 then 'NRI'  \
when cs.customer_type=12 then 'Others' end as customer_type, cs.sector,cs.document_type1,cs.document_number1,  \
lp.udf_text1, lp.udf_text2, lp.udf_text3, lp.udf_text9,lp.udf_text4,lp.udf_text5, lp.udf_text6, lp.udf_text7, lp.udf_text8,  \
cs.address1,cs.address2,cs.address3,cs.city_code,cs.state_code,cs.pin_code,cs.email,cs.phone1 as phone, cs.gstin,cs.relationship_manager, \
lp.moratorium_normal_interest_rate, concat((case when \
lp.moratorium_period_unit=1 then lp.moratorium_period_days when lp.moratorium_period_unit=2 then ROUND(lp.moratorium_period_days/7) when \
lp.moratorium_period_unit=3 then ROUND(lp.moratorium_period_days/14) when lp.moratorium_period_unit=4 then lp.moratorium_period_months \
when lp.moratorium_period_unit=5 then ROUND(lp.moratorium_period_months/3) when lp.moratorium_period_unit=6 then ROUND(lp.moratorium_period_months/6) \
when lp.moratorium_period_unit=7 then ROUND(lp.moratorium_period_months/12) end), (case when lp.moratorium_period_unit=1 \
then 'DAY' when lp.moratorium_period_unit=2 then 'WEEK' when lp.moratorium_period_unit=3 then 'FORTNIGHT' when \
lp.moratorium_period_unit=4 then 'MONTH' when lp.moratorium_period_unit=5 then 'QUARTER' when lp.moratorium_period_unit=6 \
then 'HALF_YEAR' when lp.moratorium_period_unit=7 then 'YEAR' end)) as moratoriumTenure,  \
case when lp.moratorium_type=1 then (-b.balance_magnitude+w.interest_adjustment_magnitude) else 0 end as moratoriumPayOffAmount, \
case when w.npa then w.total_normal_interest_due_magnitude+w.booked_not_due_normal_interest_magnitude else 0 end as 'NormalInterestSuspense', \
case when w.npa then w.total_penal_interest_due_magnitude+w.booked_not_due_penal_interest_magnitude else 0 end as 'PenalIneterstSuspense' ,  \
lp.udf_text11, lp.udf_text12, lp.udf_text13,lp.udf_text14, \
c.registration_no as guarantorUMRN, cs.registration_no as customerUMRN, \
lp.udf_text15 \
from banks bk,account_balances b,branches bc, \
loan_od_profiles lp  \
left join (Select f.account_id as account_id, f.tenant_code as tenant_code, \
min(case when (f.fee_category = en.name and en.reference=1) then f.fee_category else null end) as fee1_category, \
sum(case when (f.fee_category = en.name and en.reference=1) then f.amount_magnitude else null end) as fee1_amount, \
sum(case when (f.fee_category = en.name and en.reference=1) then f.gross_amount_magnitude else null end) as fee1_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=1) then f.payment_status else null end) as fee1_payment_status, \
min(case when (f.fee_category = en.name and en.reference=2) then f.fee_category else null end) as fee2_category, \
sum(case when (f.fee_category = en.name and en.reference=2) then f.amount_magnitude else null end) as fee2_amount, \
sum(case when (f.fee_category = en.name and en.reference=2) then f.gross_amount_magnitude else null end) as fee2_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=2) then f.payment_status else null end) as fee2_payment_status, \
min(case when (f.fee_category = en.name and en.reference=3) then f.fee_category else null end) as fee3_category, \
sum(case when (f.fee_category = en.name and en.reference=3) then f.amount_magnitude else null end) as fee3_amount, \
sum(case when (f.fee_category = en.name and en.reference=3) then f.gross_amount_magnitude else null end) as fee3_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=3) then f.payment_status else null end) as fee3_payment_status, \
min(case when (f.fee_category = en.name and en.reference=4) then f.fee_category else null end) as fee4_category, \
sum(case when (f.fee_category = en.name and en.reference=4) then f.amount_magnitude else null end) as fee4_amount, \
sum(case when (f.fee_category = en.name and en.reference=4) then f.gross_amount_magnitude else null end) as fee4_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=4) then f.payment_status else null end) as fee4_payment_status, \
min(case when (f.fee_category = en.name and en.reference=5) then f.fee_category else null end) as fee5_category, \
sum(case when (f.fee_category = en.name and en.reference=5) then f.amount_magnitude else null end) as fee5_amount, \
sum(case when (f.fee_category = en.name and en.reference=5) then f.gross_amount_magnitude else null end) as fee5_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=5) then f.payment_status else null end) as fee5_payment_status \
from fees f, loan_od_products p, account_profiles ap, enumerations en where f.tenant_code = en.tenant_code and en.classifier='FeeName' and \
p.tenant_code = ap.tenant_code and p.product_code = ap.product_code and \
p.product_type = 'Loans' and p.currency_code=ap.currency_code and f.account_id = ap.account_id and f.tenant_code = ap.tenant_code \
group by f.tenant_code,f.account_id) as fee_pivot on (lp.account_id = fee_pivot.account_id and lp.tenant_code = fee_pivot.tenant_code) \
left join customers c on ( lp.tenant_code = c.tenant_code \
and lp.guarantor_customer_id1 = c.customer_id), \
account_holders ah,account_profiles p, loan_od_products ps, loan_od_working_registers w  \
left join loan_od_demands d on ( w.tenant_code = d.tenant_code \
and w.account_id = d.account_id and w.oldest_due_demand_num = d.demand_num)  \
left join \
loan_od_tags lt on (w.tenant_code = lt.tenant_code and w.account_id = lt.account_id), \
customers cs  \
left join branches bcs on (bcs.tenant_code = cs.tenant_code and bcs.branch_code = cs.branch_code) \
 \
where ah.holder_num=1 and ah.tenant_code=cs.tenant_code and cs.customer_id=ah.customer_id \
and w.account_id = b.account_id and w.tenant_code = b.tenant_code \
and w.account_id = p.account_id and w.tenant_code = bc.tenant_code \
and p.branch_code=bc.branch_code and p.tenant_code = ps.tenant_code and p.product_code = ps.product_code and p.currency_code = ps.currency_code \
and w.tenant_code = p.tenant_code and lp.tenant_code=p.tenant_code and lp.account_id=p.account_id \
and ah.tenant_code=p.tenant_code and ah.account_id=p.account_id \
and bk.tenant_code = b.tenant_code and w.first_disbursement_date is not null and w.tenant_code = :tenant_code


params=tenant_code
label.tenant_code=Tenant Code
default.tenant_code=
