
header=Ac No,Original Ac No,CustomerId, Customer Name, Branch Code, BranchName,Customer Type,Address 1,Address 2,Address 3,City,State,Pin Code,Phone No,Email Id, GSTIN, PAN,\
 OpenedOnValueDate:Date, Deposit date:Date,Deposit Amount:Number,Maturity date:Date,Maturity Amount:Number, Tenure,Frequency, Interest Rate:Number, Balance:Number,Ac status,Ac closed date:Date,GL Subhead, Account Name, Product Code, \
 Tds applicable, Bank Account, Bank Name, Branch Name, Ifsc, Last Booking Date:Date, Next Booking Date:Date, Last Payout Date:Date, Next Payout Date:Date, \
 BookedNotPayableInterest:Number,BookedInterest:Number,CompoundedInterest:Number, Fresh Amount:Number, Renewal Amount:Number
 
query= select w.account_id,lp.original_account_id,ah.customer_id,\
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')) as customerName, \
p.branch_code,bc.branch_name, case when cs.customer_type=0 then 'Individual' when cs.customer_type=1 then 'Organisation' when cs.customer_type=2 then 'Public Limited'  \
when cs.customer_type=3 then 'Private Limited' when cs.customer_type=4 then 'Partnership' when cs.customer_type=5 then 'Society'  \
when cs.customer_type=6 then 'Trust' when cs.customer_type=7 then 'Government'  when cs.customer_type=8 then 'HUF'  \
when cs.customer_type=9 then 'FII' when cs.customer_type=10 then 'AOPBOI' when cs.customer_type=11 then 'NRI'  \
when cs.customer_type=12 then 'Others' end as customer_type,\
cs.address1,cs.address2,cs.address3,cs.city_code,cs.state_code,cs.pin_code,cs.phone1,cs.email, cs.gstin, cs.pan ,\
p.opened_on_value_date, w.first_deposit_date,lp.amount_magnitude,w.maturity_date, lp.maturity_amount_magnitude, \
case when \
lp.tenure_unit=1 then lp.tenure_days when lp.tenure_unit=2 then ROUND(lp.tenure_days/7) when \
lp.tenure_unit=3 then ROUND(lp.tenure_days/14) when lp.tenure_unit=4 then lp.tenure_months \
when lp.tenure_unit=5 then ROUND(lp.tenure_months/3) when lp.tenure_unit=6 then ROUND(lp.tenure_months/6) \
when lp.tenure_unit=7 then ROUND(lp.tenure_months/12) end as tenure, \
case when lp.tenure_unit=1 \
then 'DAY' when lp.tenure_unit=2 then 'WEEK' when lp.tenure_unit=3 then 'FORTNIGHT' when \
lp.tenure_unit=4 then 'MONTH' when lp.tenure_unit=5 then 'QUARTER' when lp.tenure_unit=6 \
then 'HALF_YEAR' when lp.tenure_unit=7 then 'YEAR' end as time_unit, \
lp.interest_rate, b.balance_magnitude,p.operational_status, p.closed_on_value_date,p.gl_subhead, p.account_name, p.product_code, \
lp.tax_exempted, cs.account_number1,bank_name1, branch_name1, ifsc_code1, \
w.last_booking_date, w.next_booking_date, w.last_payout_date, w.next_payout_date, booked_not_payable_interest_magnitude, booked_interest_magnitude, compounded_interest_magnitude, \
new_amount_magnitude, renewal_amount_magnitude \
from banks bk,account_balances b,branches bc, \
deposit_profiles lp,  \
account_holders ah,account_profiles p, deposit_products ps, deposit_working_registers w, \
customers cs left join branches bcs on (bcs.tenant_code = cs.tenant_code and bcs.branch_code = cs.branch_code) \
where ah.holder_num=1 and ah.tenant_code=cs.tenant_code and cs.customer_id=ah.customer_id \
and w.account_id = b.account_id and w.tenant_code = b.tenant_code \
and w.account_id = p.account_id and w.tenant_code = bc.tenant_code \
and p.branch_code=bc.branch_code and p.tenant_code = ps.tenant_code and p.product_code = ps.product_code and p.currency_code = ps.currency_code \
and w.tenant_code = p.tenant_code and lp.tenant_code=p.tenant_code and lp.account_id=p.account_id \
and ah.tenant_code=p.tenant_code and ah.account_id=p.account_id \
and bk.tenant_code = b.tenant_code and w.tenant_code = :tenant_code

params=tenant_code
label.tenant_code=Tenant Code
default.tenant_code=
