header=Ac No,Disb date,Disb Amt,Maturity date,Principal Repaid,Interest Repaid,DPD,Effective DPD,Total Fee Due ,Penal Interest Due,Late charge,Ledger Balance,Adjusted balance,Principal Due,Normal Interest Due,\
Ac status,Ac closed date,Last payment date,BookedNotDueNormalInterest,Num Demands, Num Satisfied Demands ,Tag,URN,First Repayment Date,Interest Rate,Installment,Tenure,Frequency,NextDemandScheduledDate,Net Payoff Amt,\
PrincipalNotDue,Interest TDS,Scheduled Payment,AccountName,ProductType,ProductCode,BranchCode,BranchName,PenalInterestRate,GlSubhead,OpenedOnValueDate,NextDemandRunDate,LastDemandRunDate,LastBookingDate,\
LastArchiveDate,NumAdvanceSatisfiedDemands,BookedNotDuePenalInterest,BookedNormalInterest,BookedPenalInterest,TotalDisbursedAmount,TotalRepaidAmount,TotalPenalInterestRepaid,TotalDemandDue,Total Fee Paid,\
Guarantor Customer Id,Phone No.,Open UserId,Fee1 Category,Fee1 Amount,Fee1 Gross Amount,Fee1 Payment Status,Fee2 Category,Fee2 Amount,Fee2 Gross Amount,Fee2 Payment Status,\
Fee3 Category,Fee3 Amount,Fee3 Gross Amount,Fee3 Payment Status,Fee4 Category,Fee4 Amount,Fee4 Gross Amount,Fee4 Payment ,Fee5 Category,Fee5 Amount,Fee5 Gross Amount,Fee5 Payment Status,\
Customer name,Guarantor Name,Guarantor Ph no,Customer BranchName,Asset Category,Provisioned Amount,Customer Type,Vertical,Document Type,Document Num,Primary Value Chain,Secondary Value Chain,\
Intervention,Hypothecated to,Loan Sourcing Details,K2BName/Referral Name,K2BCode/Referral Code,Samunnati Pay card,Collateral,Address 1,Address 2,Address 3,City,State,Pin Code,Phone No.,Email Id,GSTIN,RO Name,\
Moratorium Interest,MoratoriumTenure,MoratoriumPayOffAmount,NormalInterestSuspense,PenalInterestSuspense,Collateral Value,SBU,Current RM,Product Solutions,Customer UMRN,Guarantor UMRN,Subproduct,\
Max OD Days,RBI OD Days,Fee6 Category,Fee6 Amount,Fee6 Gross Amount,Fee6 Payment Status,Fee7 Category,Fee7 Amount,Fee7 Gross Amount,Fee7 Payment Status,Fee8 Category,Fee8 Amount,Fee8 Gross Amount,Fee8 Payment Status,PAN

query=select w.account_id,w.first_disbursement_date,lp.amount_magnitude,w.maturity_date,w.total_principal_repaid_magnitude,w.total_normal_interest_repaid_magnitude-w.total_interest_tds_magnitude, \
@dpd := case when w.oldest_due_demand_num = 0 then 0 else datediff(bk.current_working_date, d.demand_date) end as dpd, \
@effective_dpd := case when w.oldest_due_demand_num = 0 then 0 else case when ht.effective_date is null then datediff(bk.current_working_date, d.demand_date) \
when datediff(d.demand_date, ht.effective_date) > 0 then datediff(bk.current_working_date, d.demand_date) \
else datediff(bk.current_working_date, d.demand_date) - least(datediff(bk.current_working_date, ht.effective_date), (datediff( ht.expiry_date, ht.effective_date)+1)) \
end end as effective_dpd,w.total_fee_due_magnitude,w.total_penal_interest_due_magnitude,'',b.balance_magnitude,b.balance_magnitude, \
w.total_principal_due_magnitude,w.total_normal_interest_due_magnitude,p.operational_status, \
p.closed_on_value_date as closed_on_value_date, greatest(ifnull(w.last_repayment_date, w.last_settlement_date),ifnull(w.last_settlement_date,w.last_repayment_date)) as last_repayment_date, \
w.booked_not_due_normal_interest_magnitude,w.num_demands,w.num_satisfied_demands,lt.tag,ah.customer_id,w.first_repayment_date,lp.normal_interest_rate, \
w.installment_amount_magnitude, \
case when \
lp.tenure_unit=1 then lp.tenure_days when lp.tenure_unit=2 then ROUND(lp.tenure_days/7) when \
lp.tenure_unit=3 then ROUND(lp.tenure_days/14) when lp.tenure_unit=4 then lp.tenure_months \
when lp.tenure_unit=5 then ROUND(lp.tenure_months/3) when lp.tenure_unit=6 then ROUND(lp.tenure_months/6) \
when lp.tenure_unit=7 then ROUND(lp.tenure_months/12) end as tenure, \
case when lp.tenure_unit=1 \
then 'DAY' when lp.tenure_unit=2 then 'WEEK' when lp.tenure_unit=3 then 'FORTNIGHT' when \
lp.tenure_unit=4 then 'MONTH' when lp.tenure_unit=5 then 'QUARTER' when lp.tenure_unit=6 \
then 'HALF_YEAR' when lp.tenure_unit=7 then 'YEAR' end as time_unit, \
w.next_demand_scheduled_date,(abs(b.balance_magnitude)+w.total_normal_interest_due_magnitude+w.total_penal_interest_due_magnitude+ \
w.booked_not_due_penal_interest_magnitude+w.booked_not_due_normal_interest_magnitude+w.total_fee_due_magnitude) as NetPayoffDue, \
-b.balance_magnitude-w.total_principal_due_magnitude,w.total_interest_tds_magnitude,'',p.account_name,p.product_type, \
p.product_code,p.branch_code,bc.branch_name, lp.penal_interest_rate,p.gl_subhead,p.opened_on_value_date, \
w.next_demand_run_date,w.last_demand_run_date,w.last_booking_date,b.last_archive_date, \
w.num_advance_satisfied_demands,w.booked_not_due_penal_interest_magnitude, \
w.booked_normal_interest_magnitude,w.booked_penal_interest_magnitude, \
w.total_disbursed_magnitude,w.total_repaid_magnitude,w.total_penal_interest_repaid_magnitude, \
w.total_demand_due_magnitude,w.total_fee_repaid_magnitude,la.associate_id, ah.phone1,p.open_user_id, \
fee1_category, fee1_amount,fee1_gross_amount, fee1_payment_status,fee2_category, fee2_amount,fee2_gross_amount, fee2_payment_status, \
fee3_category, fee3_amount,fee3_gross_amount, fee3_payment_status,fee4_category, fee4_amount,fee4_gross_amount, fee4_payment_status, \
fee5_category, fee5_amount,fee5_gross_amount, fee5_payment_status, \
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')) as customerName, \
concat(COALESCE(la.first_name,''),(case when COALESCE(la.middle_name,'')='' then '' else (concat(' ',COALESCE(la.middle_name,''))) end),' ',COALESCE(la.last_name,'')) as guarantorName, \
c.phone1 as guarantorPhone1, bcs.branch_name as customerBranchName, w.asset_category, w.total_provisioned_amount_magnitude as provisionedAmount, case when \
cs.customer_type=0 then 'Individual' when cs.customer_type=1 then 'Organisation' when cs.customer_type=2 then 'Public Limited' \
when cs.customer_type=3 then 'Private Limited' when cs.customer_type=4 then 'Partnership' when cs.customer_type=5 then 'Society' \
when cs.customer_type=6 then 'Trust' when cs.customer_type=7 then 'Government'  when cs.customer_type=8 then 'HUF' \
when cs.customer_type=9 then 'FII' when cs.customer_type=10 then 'AOP/BOI' when cs.customer_type=11 then 'NRI' \
when cs.customer_type=12 then 'SHG/JLG' when cs.customer_type=13 then 'Proprietorship' else 'Others' end as customer_type, cs.sector,cs.document_type1,cs.document_number1, \
lp.udf_text1, lp.udf_text2, lp.udf_text3,lp.udf_text9, lp.udf_text4,lp.udf_text5, lp.udf_text6, lp.udf_text7, lp.udf_text8, \
cs.address1,cs.address2,cs.address3,cs.city_code,cs.state_code,cs.pin_code,cs.phone1 as phone, cs.email,cs.gstin,ca.first_name, \
lp.moratorium_normal_interest_rate, concat((case when \
lp.moratorium_period_unit=1 then lp.moratorium_period_days when lp.moratorium_period_unit=2 then ROUND(lp.moratorium_period_days/7) when \
lp.moratorium_period_unit=3 then ROUND(lp.moratorium_period_days/14) when lp.moratorium_period_unit=4 then lp.moratorium_period_months \
when lp.moratorium_period_unit=5 then ROUND(lp.moratorium_period_months/3) when lp.moratorium_period_unit=6 then ROUND(lp.moratorium_period_months/6) \
when lp.moratorium_period_unit=7 then ROUND(lp.moratorium_period_months/12) end),' ', (case when lp.moratorium_period_unit=1 \
then 'DAY' when lp.moratorium_period_unit=2 then 'WEEK' when lp.moratorium_period_unit=3 then 'FORTNIGHT' when \
lp.moratorium_period_unit=4 then 'MONTH' when lp.moratorium_period_unit=5 then 'QUARTER' when lp.moratorium_period_unit=6 \
then 'HALF_YEAR' when lp.moratorium_period_unit=7 then 'YEAR' end)) as moratoriumTenure, \
case when lp.moratorium_type=1 then (-b.balance_magnitude+w.interest_adjustment_magnitude) else 0 end as moratoriumPayOffAmount, \
case when w.npa and @dpd > lp.npa_days then w.total_normal_interest_due_magnitude+w.booked_not_due_normal_interest_magnitude else 0 end as 'NormalInterestSuspense', \
case when w.npa and @dpd > lp.npa_days then w.total_penal_interest_due_magnitude+w.booked_not_due_penal_interest_magnitude else 0 end as 'PenalInterestSuspense' , \
lp.udf_text11, lp.udf_text12, lp.udf_text13,lp.udf_text14,cs.registration_no as customerUMRN,c.registration_no as guarantorUMRN,lp.udf_text15, \
case when p.operational_status in (0,3) then max_effective_dpd else 0 end as max_od_days, \
case when p.operational_status in (0,3) then greatest(ifnull(rbi_dpd, max_effective_dpd), max_effective_dpd, ifnull(cw.marker_dpd-1+datediff(bk.current_working_date, cw.marker_date),0)) else 0 end as rbi_od_days, \
fee6_category,fee6_amount,fee6_gross_amount,fee6_payment_status, \
fee7_category,fee7_amount,fee7_gross_amount,fee7_payment_status, \
fee8_category,fee8_amount,fee8_gross_amount,fee8_payment_status, \
cs.pan \
from banks bk,account_balances b,branches bc,loan_od_profiles lp \
left join (Select f.account_id as account_id, f.tenant_code as tenant_code, \
min(case when (f.fee_category = en.name and en.reference=1) then f.fee_category else null end) as fee1_category, \
sum(case when (f.fee_category = en.name and en.reference=1) then f.amount_magnitude else null end) as fee1_amount, \
sum(case when (f.fee_category = en.name and en.reference=1) then f.gross_amount_magnitude else null end) as fee1_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=1) then f.payment_status else null end) as fee1_payment_status, \
min(case when (f.fee_category = en.name and en.reference=2) then f.fee_category else null end) as fee2_category, \
sum(case when (f.fee_category = en.name and en.reference=2) then f.amount_magnitude else null end) as fee2_amount, \
sum(case when (f.fee_category = en.name and en.reference=2) then f.gross_amount_magnitude else null end) as fee2_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=2) then f.payment_status else null end) as fee2_payment_status, \
min(case when (f.fee_category = en.name and en.reference=3) then f.fee_category else null end) as fee3_category, \
sum(case when (f.fee_category = en.name and en.reference=3) then f.amount_magnitude else null end) as fee3_amount, \
sum(case when (f.fee_category = en.name and en.reference=3) then f.gross_amount_magnitude else null end) as fee3_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=3) then f.payment_status else null end) as fee3_payment_status, \
min(case when (f.fee_category = en.name and en.reference=4) then f.fee_category else null end) as fee4_category, \
sum(case when (f.fee_category = en.name and en.reference=4) then f.amount_magnitude else null end) as fee4_amount, \
sum(case when (f.fee_category = en.name and en.reference=4) then f.gross_amount_magnitude else null end) as fee4_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=4) then f.payment_status else null end) as fee4_payment_status, \
min(case when (f.fee_category = en.name and en.reference=5) then f.fee_category else null end) as fee5_category, \
sum(case when (f.fee_category = en.name and en.reference=5) then f.amount_magnitude else null end) as fee5_amount, \
sum(case when (f.fee_category = en.name and en.reference=5) then f.gross_amount_magnitude else null end) as fee5_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=5) then f.payment_status else null end) as fee5_payment_status, \
min(case when (f.fee_category = en.name and en.reference=6) then f.fee_category else null end) as fee6_category, \
sum(case when (f.fee_category = en.name and en.reference=6) then f.amount_magnitude else null end) as fee6_amount, \
sum(case when (f.fee_category = en.name and en.reference=6) then f.gross_amount_magnitude else null end) as fee6_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=6) then f.payment_status else null end) as fee6_payment_status, \
min(case when (f.fee_category = en.name and en.reference=7) then f.fee_category else null end) as fee7_category, \
sum(case when (f.fee_category = en.name and en.reference=7) then f.amount_magnitude else null end) as fee7_amount, \
sum(case when (f.fee_category = en.name and en.reference=7) then f.gross_amount_magnitude else null end) as fee7_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=7) then f.payment_status else null end) as fee7_payment_status, \
min(case when (f.fee_category = en.name and en.reference=8) then f.fee_category else null end) as fee8_category, \
sum(case when (f.fee_category = en.name and en.reference=8) then f.amount_magnitude else null end) as fee8_amount, \
sum(case when (f.fee_category = en.name and en.reference=8) then f.gross_amount_magnitude else null end) as fee8_gross_amount, \
min(case when (f.fee_category = en.name and en.reference=8) then f.payment_status else null end) as fee8_payment_status \
from fees f, loan_od_products p, account_profiles ap,enumerations en where f.tenant_code = en.tenant_code and en.classifier='FeeName' and p.tenant_code = ap.tenant_code and p.product_code = ap.product_code and \
p.product_type = 'Loans' and f.account_id = ap.account_id and f.tenant_code = ap.tenant_code \
group by f.tenant_code,f.account_id) as fee_pivot on (lp.account_id = fee_pivot.account_id and lp.tenant_code = fee_pivot.tenant_code) \
left join loan_od_associates la on (la.tenant_code=lp.tenant_code and la.account_id=lp.account_id and la.associate_type=1 and la.sequence_num=1)\
left join customers c on ( la.tenant_code = c.tenant_code \
and la.associate_id = c.customer_id), \
account_holders ah  \
left join (select hl.tenant_code,hl.customer_id, max(case when ap.operational_status not in (0,3) or left(`lt`.`tag`, 3) = 'NPA' then 0 \
when ht.effective_date is null or datediff(nt.value_date, ht.effective_date) > nt.dpd then nt.dpd-1+datediff(bnk.current_working_date,nt.value_date) \
else greatest(nt.dpd-least(datediff(ht.expiry_date, ht.effective_date)+1,datediff(nt.value_date,ht.effective_date)),0) +datediff(bnk.current_working_date,nt.value_date) end) as rbi_dpd, \
 max(case when `lw`.`oldest_due_demand_num` = 0  or ap.operational_status not in (0,3) or left(`lt`.`tag`, 3) = 'NPA' then 0 else datediff(`bnk`.`current_working_date`, `od`.`demand_date`) end) as `max_dpd`, \
    max(case when `lw`.`oldest_due_demand_num` = 0 or ap.operational_status not in (0,3) or left(`lt`.`tag`, 3) = 'NPA' then 0 when `ht`.`effective_date` is null then datediff(`bnk`.`current_working_date`, `od`.`demand_date`) \
when  datediff(`od`.`demand_date`, `ht`.`effective_date`) > 0 then datediff(`bnk`.`current_working_date`, `od`.`demand_date`) \
else datediff(`bnk`.`current_working_date`, `od`.`demand_date`) - least(datediff(`bnk`.`current_working_date`, `ht`.`effective_date`), (datediff( `ht`.`expiry_date`, `ht`.`effective_date`)+1)) \
end) as `max_effective_dpd` \
from account_holders hl, account_profiles ap, banks bnk, loan_od_working_registers lw  \
    left join npa_transactions nt on lw.tenant_code = nt.tenant_code and lw.account_id = nt.account_id and lw.npa = 1 and lw.last_npa_marking_date = nt.value_date and nt.npa_transaction_type='NpaMarkingTransaction' \
    left join loan_od_demands od on od.tenant_code = lw.tenant_code and od.account_id = lw.account_id and od.demand_num = lw.oldest_due_demand_num \
left join `loan_od_tags` `lt` on \
(`lw`.`tenant_code` = `lt`.`tenant_code` and `lw`.`account_id` = `lt`.`account_id` and `lt`.`classifier` = 'Tagging') left join `loan_od_history_tags` `ht` on   \
          (`lw`.`tenant_code`=`ht`.`tenant_code` and `lw`.`account_id`=`ht`.`account_id` and `ht`.`classifier`='Moratorium')  \
          where hl.account_id = lw.account_id and hl.tenant_code = lw.tenant_code and bnk.tenant_code = hl.tenant_code and hl.holder_num=1 and hl.tenant_code = ap.tenant_code and hl.account_id = ap.account_id \
	  group by hl.tenant_code, hl.customer_id \
          )as rbi_od on rbi_od.tenant_code = ah.tenant_code and rbi_od.customer_id = ah.customer_id, \
account_profiles p, loan_od_products ps, loan_od_working_registers w \
left join loan_od_demands d on ( w.tenant_code = d.tenant_code \
and w.account_id = d.account_id and w.oldest_due_demand_num = d.demand_num) \
left join \
loan_od_tags lt on (w.tenant_code = lt.tenant_code and w.account_id = lt.account_id and lt.classifier = 'Tagging') left join loan_od_history_tags ht on \
            (w.tenant_code=ht.tenant_code and w.account_id=ht.account_id and ht.classifier='Moratorium'), \
customers cs \
left join branches bcs on (bcs.tenant_code = cs.tenant_code and bcs.branch_code = cs.branch_code) \
left join customer_associates ca join banks bkca on ca.tenant_code = bkca.tenant_code and ca.effective_date <= bkca.current_working_date and ca.expiry_date > bkca.current_working_date \
	on cs.tenant_code=ca.tenant_code and cs.customer_id=ca.customer_id and ca.associate_type=1, customer_working_registers cw \
where ah.holder_num=1 and ah.tenant_code=cs.tenant_code and cs.customer_id=ah.customer_id \
and w.account_id = b.account_id and w.tenant_code = b.tenant_code \
and w.account_id = p.account_id and w.tenant_code = bc.tenant_code \
and p.branch_code=bc.branch_code and p.tenant_code = ps.tenant_code and p.product_code = ps.product_code \
and w.tenant_code = p.tenant_code and lp.tenant_code=p.tenant_code and lp.account_id=p.account_id \
and ah.tenant_code=p.tenant_code and ah.account_id=p.account_id \
and cw.customer_id=cs.customer_id and cw.tenant_code = cs.tenant_code \
and bk.tenant_code = b.tenant_code and w.first_disbursement_date is not null and w.tenant_code=:tenant_code

params=tenant_code
label.tenant_code=Tenant Code
default.tenant_code=

