header=Ac num,Disbursement date,Loan Amount,Maturity date,Principal Repaid,Normal Interest repaid,DPD,Advance Installment,Fee due,Penal interest Due,\
 Tag,Ledger balance,Asset category,Principal due,Normal interest due,Ac status,Ac closed date,Last repayment date,\
 BookedNotDueNormalInterest,Demands raised,Demands satisfied,Old Ac num,CustomerId,First repayment date,Normal interest rate,Installment amount,\
 Tenure,Frequency,NextDemandScheduledDate,Net Payoff Amount,PrincipalNotDue,AdvanceInterest,OldestDueDemandNum,\
 AccountName,ProductType,ProductCode,BranchCode,PenalInterestRate,GlSubhead,OpenedOnValueDate,NextDemandRunDate,LastDemandRunDate,LastBookingDate,\
 LastArchiveDate,NumAdvanceSatisfiedDemands,BookedNotDuePenalInterest,BookedNormalInterest,BookedPenalInterest,TotalDisbursedAmount,TotalRepaidAmount,\
 TotalPenalInterestRepaid,TotalDemandDue,Total Fee Paid,Security Deposit,NPA,BookedNotDueAdditionalInterest,BookedAdditionalInterest,AdditionalInterestDue,AdditionalInterestRepaid

query=select w.account_id,DATE_FORMAT(w.first_disbursement_date,'%Y-%m-%d'),lp.amount_magnitude,DATE_FORMAT(w.maturity_date,'%Y-%m-%d'), \
			w.total_principal_repaid_magnitude,w.total_normal_interest_repaid_magnitude, \
			case when w.oldest_due_demand_num = 0 then 0 else datediff(bk.current_working_date, d.demand_date) end as dpd, \
			w.security_deposit_installment_magnitude,w.total_fee_due_magnitude,w.total_penal_interest_due_magnitude,lt.tag, \
			b.balance_magnitude,w.asset_category,w.total_principal_due_magnitude,w.total_normal_interest_due_magnitude,p.operational_status, \
			DATE_FORMAT(p.closed_on_transaction_date,'%Y-%m-%d'), DATE_FORMAT(w.last_repayment_date,'%Y-%m-%d'), \
			w.booked_not_due_normal_interest_magnitude,w.num_demands,w.num_satisfied_demands,lp.original_account_id, \
			ah.customer_id,DATE_FORMAT(w.first_repayment_date,'%Y-%m-%d'),lp.normal_interest_rate, w.installment_amount_magnitude,\
			case when lp.tenure_unit=1 then lp.tenure_days \
			when lp.tenure_unit=2 then ROUND(lp.tenure_days/7) when lp.tenure_unit=3 then ROUND(lp.tenure_days/14) \
			when lp.tenure_unit=4 then lp.tenure_months when lp.tenure_unit=5 then ROUND(lp.tenure_months/3) \
			when lp.tenure_unit=6 then ROUND(lp.tenure_months/6) when lp.tenure_unit=7 then ROUND(lp.tenure_months/12) end as tenure, \
			case when lp.tenure_unit=1 then 'DAY' when lp.tenure_unit=2 then 'WEEK' \
			when lp.tenure_unit=3 then 'FORTNIGHT' when lp.tenure_unit=4 then 'MONTH' when lp.tenure_unit=5 then 'QUARTER' \
			when lp.tenure_unit=6 then 'HALF_YEAR' when lp.tenure_unit=7 then 'YEAR' end as time_unit, \
			DATE_FORMAT(w.next_demand_scheduled_date,'%Y-%m-%d'),(abs(b.balance_magnitude)+ w.total_normal_interest_due_magnitude+w.total_penal_interest_due_magnitude+ \
			w.booked_not_due_penal_interest_magnitude+w.booked_not_due_normal_interest_magnitude+w.total_fee_due_magnitude) as NetPayoffDue, \
			-b.balance_magnitude-w.total_principal_due_magnitude,w.security_deposit_advance_interest_magnitude, w.oldest_due_demand_num,p.account_name,p.product_type, \
			p.product_code,p.branch_code, lp.penal_interest_rate,p.gl_subhead,DATE_FORMAT(p.opened_on_value_date,'%Y-%m-%d'), \
			DATE_FORMAT(w.next_demand_run_date,'%Y-%m-%d'),DATE_FORMAT(w.last_demand_run_date,'%Y-%m-%d'),DATE_FORMAT(w.last_booking_date,'%Y-%m-%d'),DATE_FORMAT(b.last_archive_date,'%Y-%m-%d'), \
			w.num_advance_satisfied_demands,w.booked_not_due_penal_interest_magnitude,w.booked_normal_interest_magnitude,w.booked_penal_interest_magnitude, \
			w.total_disbursed_magnitude,w.total_repaid_magnitude,w.total_penal_interest_repaid_magnitude,w.total_demand_due_magnitude,w.total_fee_repaid_magnitude, \
			w.security_deposit_magnitude,w.npa,w.booked_not_due_additional_interest_magnitude,w.booked_additional_interest_magnitude, \
			w.total_additional_interest_due_magnitude,w.total_additional_interest_repaid_magnitude \
			from banks bk,account_balances b,loan_od_profiles lp,account_holders ah,account_profiles p, loan_od_working_registers w \
			left join loan_od_demands d on ( w.tenant_code = d.tenant_code and w.account_id = d.account_id and w.oldest_due_demand_num = d.demand_num) \
			left join loan_od_tags lt on (w.tenant_code = lt.tenant_code and w.account_id = lt.account_id and `lt`.`classifier` = 'Tag') \
			where ah.holder_num=1 and w.account_id = b.account_id and w.tenant_code = b.tenant_code \
			and w.account_id = p.account_id and w.tenant_code = p.tenant_code and lp.tenant_code=p.tenant_code and lp.account_id=p.account_id \
			and ah.tenant_code=p.tenant_code and ah.account_id=p.account_id and bk.tenant_code = b.tenant_code and (p.operational_status=0 or \
			p.closed_on_transaction_date=DATE_SUB(bk.current_working_date,INTERVAL 1 DAY) or p.operational_status=3) and w.tenant_code = :tenant_code

params=tenant_code
label.tenant_code=Tenant Code
default.tenant_code=