header=AccountId,CustomerId,CustomerName,BranchCode,ProductCode,FromDate,ToDate,Days,Balance,InterestRate,InterestType,Interest

query=select ic.account_id, ah.customer_id,\
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')), ap.branch_code,ap.product_code, \
greatest(:from_date, ic.start_date), least(:to_date, ic.computation_date), datediff(least(:to_date, ic.computation_date),greatest(:from_date, ic.start_date))+1,ic.amount_magnitude, ic.interest_rate, case when ic.interest_type = 0 then 'Normal Interest' when ic.interest_type = 1 then 'Penal Interest' else 'Other Interest' end, \
ic.interest_magnitude/ic.tenure_days * (datediff(least(ic.computation_date, :to_date), greatest(ic.start_date, :from_date)) + 1) \
from interest_computations ic,account_profiles ap, account_holders ah, branchset_branches bs where \
				ic.tenant_code = :tenant_code and \
				((:from_date >= ic.start_date and :from_date <= ic.computation_date) or \
				(:to_date >= ic.start_date and :to_date <= ic.computation_date) or \
				(:from_date < ic.start_date and :to_date > ic.computation_date)) and \
				ic.account_id = case when :account_id_text is null then ic.account_id when :account_id_text = '' then ic.account_id else :account_id_text end and \
				ic.tenant_code = ap.tenant_code and ic.account_id = ap.account_id and ic.tenant_code = ah.tenant_code and ic.account_id = ah.account_id and ah.holder_num = 1 and \
				ap.tenant_code = bs.tenant_code and ap.branch_code = bs.branch_code and bs.branchset_code = :branchset_code_select order by ic.tenant_code,ic.account_id,ic.interest_type,ic.start_date

params=tenant_code,branchset_code_select,from_date,to_date,account_id_text
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
label.branchset_code_select=BranchSet
default.branchset_code_select=All
label.account_id_text=AccountId(optional)
default.account_id_text=
