header=AccountId,CustomerId,CustomerName,BranchCode,ProductCode,InterestType,Interest:Number

query=select ap.account_id, ah.customer_id,\
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')), \
ap.branch_code,ap.product_code, case when ic.interest_type = 0 then 'Normal Interest' when ic.interest_type = 1 then 'Penal Interest' else 'Other Interest' end, sum(ic.interest) from \
        ( select tenant_code,account_id,interest_type,interest_magnitude/tenure_days * (datediff(least(computation_date, :to_date), greatest(start_date, :from_date)) + 1) as interest \
                from interest_computations where tenant_code = :tenant_code and \
                                ((:from_date >= start_date and :from_date <= computation_date) or \
                                (:to_date >= start_date and :to_date <= computation_date) or \
                                (:from_date < start_date and :to_date > computation_date))) ic, \
        account_profiles ap, account_holders ah, branchset_branches bs where \
                                ic.tenant_code = ap.tenant_code and ic.account_id = ap.account_id and ic.tenant_code = ah.tenant_code and ic.account_id = ah.account_id and ah.holder_num = 1 and \
                                ap.tenant_code = bs.tenant_code and ap.branch_code = bs.branch_code and bs.branchset_code = :branchset_code_select group by ic.tenant_code,ic.account_id,ic.interest_type \
                                order by ic.tenant_code,ic.account_id,ic.interest_type

params=tenant_code,branchset_code_select,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
label.branchset_code_select=BranchSet
default.branchset_code_select=All
