header=Value Date, Account Name, Account Id, Entry Type, Instrument, Instrument Ref, Transaction Date, Narration, Debit Amount, Credit Amount, Currency, Transaction Source

query=select be.value_date as value_date, null as account_name, null as account_id, be.account_entry_type as entry_type, \
null as instrument, be.reference as instrument_ref, be.transaction_date as transaction_date, be.narration as narration, \
if(be.account_entry_type=0, null, be.amount_magnitude) as debit_amount, \
if(be.account_entry_type=0, be.amount_magnitude, null) as credit_amount, \
be.amount_currency as currency, 'Bank' as transaction_source from  recon_bank_account_entries be where be.linked_account_code=:accountCode_text \
and be.tenant_code=:tenant_code and be.status=0 \
union all \
select ae.value_date as value_date, concat(ah.first_name, ah.last_name) as account_name,   ap.account_id as account_id, \
ae.account_entry_type as account_entry_type, ae.instrument as instrument,  ae.instrument_ref as instrument_ref, \
ae.transaction_date as transaction_date, ae.description as narration, \
if(ae.account_entry_type=0, null, ae.amount_magnitude) as debit_amount, \
if(ae.account_entry_type=0, ae.amount_magnitude, null) as credit_amount, \
ae.amount_currency as currency, 'GL' as transaction_source \
 from account_entries ae inner join account_profiles ap \
on ae.account_id=ap.account_id and ae.tenant_code=ap.tenant_code \
left join account_holders ah on ap.tenant_code=ah.tenant_code and  ap.account_id=ah.account_id and ah.holder_num=1 \
inner join branches b on ap.tenant_code=b.tenant_code and ap.branch_code=b.branch_code  and b.is_hq=1 \
where ap.product_type='Internal' and ap.product_code=:accountCode_text and ap.tenant_code=:tenant_code and ae.recon_entry_status=0

params=tenant_code,accountCode_text
label.tenant_code=Tenant Code
default.tenant_code=
label.accountCode_text=Account Code
default.accountCode_text= 