header=Ac num,CustomerId,Branch Code,Product Code,Demand Num:number,Demand Date:date, Transaction Date:date, Transaction Id, Amount:number,Principal:number,Normal Interest: number, Penal Interest:number,Amount Repaid:number, Principal Repaid:number, Normal Interest Repaid:number, Penal Interest Repaid:number, Collection Efficiency:number, Created At, Created By
 
query=select ld.account_id, ah.customer_id, ap.branch_code, ap.product_code, ld.demand_num, ld.demand_date, ld.transaction_date, ld.transaction_id, \
ld.amount_magnitude,ld.principal_magnitude,ld.normal_interest_magnitude,ld.penal_interest_magnitude,ifnull(t.amount_magnitude,0), ifnull(t.principal_magnitude,0), \
ifnull(t.normal_interest_magnitude,0), ifnull(t.penal_interest_magnitude,0), least(round(ifnull(t.amount_magnitude,0)/ld.amount_magnitude*100,2),100) as collection_efficiency, ld.created_at, ld.created_by \
from loan_od_demands ld left join (select tenant_code, account_id, demand_num, sum(amount_magnitude) as amount_magnitude, sum(principal_magnitude) as principal_magnitude, \
  sum(normal_interest_magnitude) as normal_interest_magnitude, sum(penal_interest_magnitude) as penal_interest_magnitude from loan_od_fulfillments lf group by tenant_code,account_id, demand_num) t on t.account_id=ld.account_id and t.tenant_code=ld.tenant_code and t.demand_num = ld.demand_num, \
account_holders ah, account_profiles ap, branchset_branches bs \
where ap.branch_code=bs.branch_code and ap.tenant_code=bs.tenant_code \
and ld.account_id=ah.account_id and ld.tenant_code=ah.tenant_code and ah.holder_num=1 \
and ld.account_id=ap.account_id and ld.tenant_code=ap.tenant_code \
and bs.branchset_code = :branchset_code_select and ld.transaction_date >= :from_date and ld.transaction_date <= :to_date \
group by ld.tenant_code,ld.account_id,ld.demand_num

params=tenant_code,branchset_code_select,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=Branchset
default.branchset_code_select=All
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=

