

header=Consumer Name,Date of Birth,Gender,Income Tax ID Number,Passport Number,Passport Issue Date,Passport Expiry Date,Voter ID Number,Driving License Number,\
Driving License Issue Date,Driving License Expiry Date,Ration Card Number,Universal ID Number,Additional ID #1,Additional ID #2,Telephone No.Mobile,\
Telephone No.Residence,Telephone No.Office,Extension Office,Telephone No.Other,Extension Other,Email ID 1,Email ID 2,Address 1,State Code 1,PIN Code 1,\
Address Category 1,Residence Code 1,Corresponding Add,State Code 2,PIN Code 2,Address Category 2,Residence Code 2,Current/New Member Code,\
Current/New Member Short Name,Curr/New Account No,Account Type,Ownership Indicator,Date Opened/Disbursed,Date of Last Payment,Date Closed, \
Date Reported,High Credit/Sanctioned Amt,Current  Balance,Amt Overdue,No of Days Past Due,Old Mbr Code,Old Mbr Short Name,Old Acc No,Old Acc Type,\
Old Ownership Indicator,Suit Filed / Wilful Default,Written-off and Settled Status,Asset Classification,Value of Collateral,Type of Collateral,\
Credit Limit,Cash Limit,Rate of Interest,RepaymentTenure,EMI Amount,Written- off Amount (Total) ,Written- off Principal Amount,Settlement Amt,\
Payment Frequency,Actual Payment Amt,Occupation Code,Income,Net/Gross Income Indicator,Monthly/Annual Income Indicator

query=select c.first_name,c.middle_name,c.last_name, DATE_FORMAT(c.date_of_birth,'%d%m%Y'), case when (c.gender='F' or c.gender='Female') then 1 when (c.gender='M' or c.gender='Male') then 2 else 3 end as Gender, \
			c.pan,'','','',document_number1,document_number2,'','',document_number3,c.uid_num,'','', c.phone1, c.phone2, '','','','',c.email,'', \
			REPLACE(concat(COALESCE(c.address1,''),' ',COALESCE(c.address2,''),' ',COALESCE(c.address3,'')),',',' ')  as address, \
			case when s.state_name='Jammu & Kashmir' then '01' when s.state_name='Himachal Pradesh' then '02' when s.state_name='Punjab' then '03' \
			when s.state_name='Chandigarh' then '04' when s.state_name in ('Uttaranchal','Uttarakhand') then '05' when s.state_name='Haryana' then '06' \
			when s.state_name='Delhi' then '07' when s.state_name='Rajasthan' then '08' when s.state_name='Uttar Pradesh' then '09' \
			when s.state_name='Bihar' then '10' when s.state_name='Sikkim' then '11' when s.state_name='Arunachal Pradesh' then '12' \
			when s.state_name='Nagaland' then '13' when s.state_name='Manipur' then '14' when s.state_name='Mizoram' then '15' \
			when s.state_name='Tripura' then '16' when s.state_name='Meghalaya' then '17' when s.state_name='Assam' then '18' \
			when s.state_name='West Bengal' then '19' when s.state_name='Jharkhand' then '20' when s.state_name= 'Odisha' then '21' \
			when s.state_name='Chhattisgarh' then '22' when s.state_name='Madhya Pradesh' then '23' when s.state_name='Gujarat' then '24' \
			when s.state_name='Daman & Diu' then '25' when s.state_name='Dadra & Nagar Haveli' then '26' when s.state_name='Maharashtra' then '27' \
			when s.state_name='Andhra Pradesh' then '28' when s.state_name='Karnataka' then '29' when s.state_name='Goa' then '30' \
			when s.state_name='Lakshadweep' then '31' when s.state_name='Kerala' then '32' when s.state_name='Tamil Nadu' then '33' \
			when s.state_name='Pondicherry' then '34' when s.state_name='Andaman & Nicobar Islands' then '35' when s.state_name='Telangana' then '36' else '99' end as stateCode, \
			c.pin_code, case when c.address_type='Permanent' then '01' when (c.address_type='Communication' or c.address_type='Present') then '02' when c.address_type='Office' \
			then '03' else '04' end as addressType,'','','','','','', 'NB77920001' as memberCode,'SAMUNNATIFI' as memberShortName, \
			l.account_id, case when c.sector='Agri Enterprises' then '51' else '53' end as accountType, case when c.customer_type=0 then '1' else '0' end as ownerShipIndicator, \
			DATE_FORMAT(w.first_disbursement_date,'%d%m%Y'), DATE_FORMAT(w.last_repayment_date,'%d%m%Y'),DATE_FORMAT(ap.closed_on_value_date,'%d%m%Y'), \
			DATE_FORMAT(b.current_working_date,'%d%m%Y'),round(l.amount_magnitude,0), case when (round(abs(ab.balance_magnitude),0)<=500) then 0 else \
			round(abs(ab.balance_magnitude),0) end as currentBalance, round(w.total_demand_due_magnitude,0) as amountOverDue, case when w.oldest_due_demand_num = 0 then 0 \
			when (ap.operational_status=3 and ap.last_freezed_date is not null ) then datediff(ap.last_freezed_date, d.demand_date) else datediff(b.current_working_date, d.demand_date) end as dpd, \
			'','','','','','','',case when w.asset_category='STANDARD' \
			then '01' when w.asset_category='SUBSTANDARD' then '02' when w.asset_category='DOUBTFUL' then '03' when w.asset_category='LOSS' \
			then '04' else '05' end as assetCategory, '','','','',round(l.normal_interest_rate*100,0),l.tenure_months,round(w.installment_amount_magnitude,0),'','','', \
			case when l.tenure_unit=1 then '06' when l.tenure_unit=2 then '01' when l.tenure_unit=3 then '02' when l.tenure_unit=4 then '03' \
			when l.tenure_unit=5 then '04' when l.tenure_unit=6 then '07' when l.tenure_unit=7 then '08' else '09' end as fequency,'','','','','' \
			from customers c, account_holders h, loan_od_profiles l,loan_od_working_registers w left join loan_od_demands d on \
			(w.tenant_code = d.tenant_code and w.account_id = d.account_id and w.oldest_due_demand_num = d.demand_num),banks b, account_balances ab, account_profiles ap, states s \
			where c.tenant_code=s.tenant_code and c.tenant_code=h.tenant_code and h.tenant_code=l.tenant_code and l.tenant_code=w.tenant_code \
			and l.tenant_code=b.tenant_code and b.tenant_code=ab.tenant_code and ab.tenant_code=ap.tenant_code and ab.account_id=ap.account_id and \
			l.account_id=ab.account_id and c.state_code=s.state_code and c.customer_id=h.customer_id and h.account_id=l.account_id and \
			l.account_id=w.account_id and c.date_of_birth is not null  and ((c.phone1 is not null and c.phone1 != '' and c.phone1 != '0') or \
			(c.phone2 is not null and c.phone2 != '' and c.phone2 != '0')) and ((c.pan !='' and c.pan is not null) or (c.uid_num!='' and c.uid_num is not null) \
			or (document_number1 is not null and document_number1 !='') or (document_number2 is not null and document_number2 !='') \
			or (document_number3 is not null and document_number3 !='')) and c.customer_type='0' and c.last_name not like '%SHG%' and \
            c.last_name not like '%JLG%' and c.last_name not like '%LIMITED%' and w.first_disbursement_date is not null and c.tenant_code = :tenant_code

params=tenant_code
label.tenant_code=Tenant Code
default.tenant_code=


			