query=select customer_id, first_name, middle_name, last_name, customer_type, gender, branch_code, address1, address2, address3, city_code, state_code, pin_code, phone1, phone2, email from customers where tenant_code = :tenant_code and branch_code in (select branch_code from branchset_branches where branchset_code = :branchset_code_select)
header=customerId,firstName,middleName,lastName,customerType,gender,branchCode,address1,address2,address3,city,state,pin,phone1,phone2,email
params=tenant_code,branchset_code_select
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=Branchset
default.branchset_code_select=All