header=Ac num,CustomerId,Branch Code,Product Code,Demand Num,Type,Demand Date, Value Date, Transaction Date, Transaction Id, Transaction Name, Amount, Balance, Principal, Normal Interest, \
 Penal Interest, Reference, Created At, Created By, Repayment Date, Repaid Amount, Repayment Type, Instrument, Account Code, User

query=\
select account_id,customer_id,branch_code,product_code,demand_num,demand_type,demand_date,value_date,transaction_date,transaction_id,transaction_name,amount_magnitude,balance_magnitude,principal_magnitude,normal_interest_magnitude, \
penal_interest_magnitude,reference,created_at,created_by,repayment_date,repayment_magnitude,repayment_type,instrument,account_code,user_id from ( \
\
select ld.tenant_code, ld.account_id, ah.customer_id, ap.branch_code, ap.product_code, ld.demand_num, 'Due' as demand_type, ld.demand_date as demand_date, ld.demand_scheduled_date as value_date, ld.transaction_date, \
ld.transaction_id, 'Demand' as transaction_name,ld.amount_magnitude - ifnull(t.amount_magnitude,0) as amount_magnitude, ld.balance_magnitude, ld.principal_magnitude-ifnull(t.principal_magnitude,0) as principal_magnitude, \
ld.normal_interest_magnitude-ifnull(t.normal_interest_magnitude,0) as normal_interest_magnitude, ld.penal_interest_magnitude-ifnull(t.penal_interest_magnitude,0) as penal_interest_magnitude, '' as reference, ld.created_at, ld.created_by, \
'' as repayment_date, '' as repayment_magnitude, '' as repayment_type, 'CASH' as instrument, '' as account_code, '' as user_id from loan_od_demands ld left join (select tenant_code, account_id, demand_num, sum(amount_magnitude) as amount_magnitude, sum(principal_magnitude) as principal_magnitude, \
sum(normal_interest_magnitude) as normal_interest_magnitude, sum(penal_interest_magnitude) as penal_interest_magnitude from loan_od_fulfillments lf group by tenant_code,account_id, demand_num) t on t.account_id=ld.account_id and t.tenant_code=ld.tenant_code and t.demand_num = ld.demand_num, \
account_holders ah, account_profiles ap, loan_od_working_registers w, branchset_branches bs \
where ap.branch_code=bs.branch_code and ap.tenant_code=bs.tenant_code \
and ld.account_id=ah.account_id and ld.tenant_code=ah.tenant_code and ah.holder_num=1 \
and ld.account_id=ap.account_id and ld.tenant_code=ap.tenant_code and w.tenant_code = ap.tenant_code and w.account_id = ap.account_id \
and bs.branchset_code = :branchset_code_select and w.oldest_due_demand_num > 0 and ap.operational_status = 0 and ld.scheduled_demand = 1 \
group by ld.tenant_code,ld.account_id,ld.demand_num \
\
) t where amount_magnitude > 0 order by tenant_code,account_id,demand_num

params=tenant_code,branchset_code_select
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=Branchset
default.branchset_code_select=All
