
header=Account Number,URN No.,Branch Code,Product Code ,Disbursement Date,Transaction Date,Disbursement Amount,UserID,Net Disbursement Amount,Customer Name,Vertical,Branch Name,Account Name,Fee1 Amount,Fee1 Gross Amount,Fee2 Amount,Fee3 Amount,Guarantor Name

query=SELECT ah.customer_id,ld.account_id,ap.product_code,ap.branch_code,b.branch_name, \
ld.amount_magnitude,ld.value_date,ld.transaction_date,ld.user_id,ld.net_disbursement_magnitude, \
concat(COALESCE(ah.first_name,''),' ',COALESCE(ah.middle_name,''),' ',COALESCE(ah.last_name)) as customerName,c.sector, \
ap.account_name, f1.amount_magnitude as fee1_net_amount,f1.gross_amount_magnitude as fee1_amount, f2.gross_amount_magnitude as fee2_amount, f3.gross_amount_magnitude as fee3_amount , \ 
concat(COALESCE(cs.first_name,''),' ',COALESCE(cs.middle_name,''),' ',COALESCE(cs.last_name)) as guarantorName \
FROM \
loan_od_profiles lp left join customers cs on (lp.tenant_code=cs.tenant_code and lp.guarantor_customer_id1=cs.customer_id), \ 
account_profiles ap  \
left join loan_od_products pd on (ap.tenant_code=pd.tenant_code and ap.product_code=pd.product_code ) \
left join loan_od_disbursements ld on (ld.tenant_code=ap.tenant_code  and ld.account_id=ap.account_id ) \
left join fees f1 on (f1.tenant_code=ap.tenant_code and f1.account_id=ap.account_id and f1.fee_category=(Select en.name from enumerations en where en.tenant_code=f1.tenant_code and en.reference=1 and en.classifier='FeeName') \
 and ld.transaction_id=f1.charged_transaction_id ) \
left join fees f2 on (f2.tenant_code=ap.tenant_code and f2.account_id=ap.account_id and f2.fee_category=(Select en.name from enumerations en where en.tenant_code=f1.tenant_code and en.reference=2 and en.classifier='FeeName') \
 and ld.transaction_id=f2.charged_transaction_id ) \
left join fees f3 on (f3.tenant_code=ap.tenant_code and f3.account_id=ap.account_id and f3.fee_category=(Select en.name from enumerations en where en.tenant_code=f1.tenant_code and en.reference=3 and en.classifier='FeeName') \
 and ld.transaction_id=f3.charged_transaction_id ) , \
account_holders ah,branches b,branchset_branches bs, customers c \
where ld.tenant_code=lp.tenant_code and ah.tenant_code=c.tenant_code and ah.tenant_code=c.tenant_code and ld.tenant_code=ap.tenant_code \ 
and ld.tenant_code=bs.tenant_code and ah.holder_num=1 and ld.account_id=ap.account_id and ap.tenant_code=ah.tenant_code and \
ap.account_id=ah.account_id and ah.tenant_code=b.tenant_code and ap.branch_code=b.branch_code and ap.branch_code=bs.branch_code and \ 
ah.customer_id=c.customer_id and ld.account_id=lp.account_id and bs.branchset_code =:branchset_code_select and ap.tenant_code=:tenant_code and \ 
(ld.transaction_date>=DATE_ADD(DATE_SUB(DATE_SUB(:to_date,INTERVAL 1 DAY),interval day(DATE_SUB(:to_date,INTERVAL 1 DAY)) day), interval 1 day) and ld.transaction_date<=DATE_SUB(:to_date,INTERVAL 1 DAY))

params=tenant_code,to_date,branchset_code_select
label.tenant_code=Tenant Code
default.tenant_code=
label.to_date=To Date
default.to_date=
label.branchset_code_select=BranchSet Code
default.branchset_code_select=All