header=Branch code,GL Subhead,GL Code,Product Code,Product Description, Account Id, Value Date:date,Transaction Date:date,Transaction Id,Description,Referenced Account Id,Instrument,Instrument Ref,Debit Amount:number,Credit Amount:number

query=select ap.branch_code,p.gl_subhead, p.gl_code,p.product_code, p.product_description,case when p.product_type = 'Internal' then '' else ap.account_id end, e.value_date, e.transaction_date, e.transaction_id, description, e.referenced_account_id, e.instrument,e.instrument_ref, \
case when account_entry_type = 1  then amount_magnitude else 0 end as debit_amount,case when account_entry_type = 0  then amount_magnitude else 0 end as credit_amount \
from account_entries e, account_profiles ap, products p, branchset_branches bsb where e.account_id = ap.account_id and e.tenant_code = ap.tenant_code and \
ap.tenant_code = p.tenant_code and ap.product_type = p.product_type and ap.product_code = p.product_code and ap.currency_code = p.currency_code and \
e.tenant_code = :tenant_code and e.value_date >= :from_date and e.value_date <= :to_date and p.product_type = 'Internal' and p.gl_code = :gl_code and \
ap.branch_code = bsb.branch_code and ap.tenant_code = bsb.tenant_code and bsb.branchset_code = :branchset_code_select

params=tenant_code,branchset_code_select,gl_code,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=Branchset
default.branchset_code_select=All
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
label.gl_code=GL Code
default.gl_code=