header=GL Head,GL Subhead,Product Type, Product/Account Code, Description, GL Code, Category, Balance, Currency

query=select gl.gl_head, ap.gl_subhead,ap.product_type,ap.product_code,p.product_description,p.gl_code,p.category, SUM(ab.balance_magnitude), ap.currency_code \
from account_balances ab, account_profiles ap, gl_subheads gl, products p where ap.product_code = p.product_code and ab.account_id = ap.account_id and ap.gl_subhead = gl.gl_subhead \
and ab.balance_magnitude <> 0 and ap.tenant_code = p.tenant_code and ab.tenant_code = ap.tenant_code and ab.tenant_code = :tenant_code and ap.branch_code in (select b.branch_code from branchset_branches b \
where b.branchset_code = :branchset_code_select and b.tenant_code = :tenant_code) group by gl.gl_head,ap.gl_subhead,ap.product_type,ap.product_code,ap.currency_code,ap.tenant_code order by gl.gl_head

params=tenant_code,branchset_code_select
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=BranchSet
default.branchset_code_select=All
