header=Value Date, AccountId,Product Code,Branch Code,Currency Code,Balance

query=select :from_date,p.account_id, p.product_code,p.branch_code as branch_code,p.currency_code,ifnull(amount_credit - amount_debit,0) as balance from account_profiles p left join \
( select ap.tenant_code, ap.account_id, \
   greatest(sum(CASE when account_entry_type = 0 then amount_magnitude else -amount_magnitude end),0) as amount_credit, \
   greatest(sum(CASE when account_entry_type = 1 then amount_magnitude else -amount_magnitude end),0) as amount_debit \
from account_entries e, account_profiles ap, banks b \
where e.tenant_code = ap.tenant_code and e.account_id = ap.account_id and e.value_date <= :from_date \ 
and b.tenant_code = ap.tenant_code \
group by ap.tenant_code, ap.account_id ) t on t.tenant_code = p.tenant_code and t.account_id = p.account_id where \
p.product_type = 'Loans' 

params=tenant_code,from_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=