
header=Account Number,Customer Id,Product Code,Branch Code,Branch Name ,Value Date,Transaction Date,Restricted Amount,Original Amount, Customer Name,User Id

query=SELECT ld.account_id,ah.customer_id,ap.product_code,ap.branch_code,b.branch_name, ld.value_date,ld.transaction_date,ld.amount_magnitude,ld.old_loan_amount_magnitude, \
concat(COALESCE(ah.first_name,''),' ',COALESCE(ah.middle_name,''),' ',COALESCE(ah.last_name)) as customerName,ld.user_id \
from loan_od_amendments ld, account_profiles ap, account_holders ah, branches b, branchset_branches bs where ld.tenant_code = ap.tenant_code and ld.account_id = ap.account_id and \
ap.tenant_code = ah.tenant_code and ap.account_id = ah.account_id and ah.holder_num = 1 and b.tenant_code = ap.tenant_code and b.branch_code = ap.branch_code and \
b.tenant_code = bs.tenant_code and b.branch_code = bs.branch_code and ld.amendment_type = 14 and bs.branchset_code =:branchset_code_select and ld.tenant_code=:tenant_code and and ld.value_date >= :from_date and ld.value_date <= :to_date

params=tenant_code,to_date,branchset_code_select
label.tenant_code=Tenant Code
default.tenant_code=
label.to_date=To Date
default.to_date=
label.branchset_code_select=BranchSet Code
default.branchset_code_select=All