header=Entity Type,Entity Id,Action,Old Value, New Value, Difference, Status, Checked At, Checked By, Checked Remarks, Created At, Created By

query=select entity_type,entity_id,action_type,old_json,new_json,diff_json,status, checked_at,checked_by,checked_remarks, created_at,created_by from maker_checker_master_actions \
where tenant_code=:tenant_code and DATE(created_at) >= :from_date and DATE(created_at) <= :to_date

params=tenant_code,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=

