
header=Payment identifier, Amount, Value Date, Beneficiary Name, Bene Account Number, Email ID of beneficiary, Email Body, \
       Debit Account Number, CRN (Narration / Remarks), Receiver IFSC, Receiver A/c type, Remarks (Beneficiary Account Stmt narration)

query=select 'N' as paymentIdentifier,ld.net_disbursement_magnitude,ld.value_date,ae.party_info,ae.bank_account_number,'' as benfEmailId,'' as emailBody, \
		ld.account_id,ld.account_id, ae.ifsc_code, '11' as receiverAcType,ld.account_id \
		from loan_od_disbursements ld, account_profiles ap, account_entries ae, account_holders ah \
		where ld.tenant_code=ap.tenant_code and ap.tenant_code=ae.tenant_code and ld.tenant_code=ah.tenant_code and ld.instrument=5 and \
		ld.account_code=ap.product_code and ap.account_id=ae.account_id and ld.account_id=ah.account_id and ld.transaction_id=ae.transaction_id and ah.holder_num=1 and \
 		ld.feed_file_name is null and ap.product_code= :account_code_select and ah.tenant_code=:tenant_code and ld.value_date >= :from_date and ld.value_date <= :to_date

params=tenant_code,from_date,to_date,account_code_select
label.tenant_code=Tenant Code
label.from_date=From Date
label.to_date=To Date
label.account_code_select=Account Code
default.tenant_code=