
header=BV_WorkingDate_BranchID_SlNo,BRNET,Sl No,SlNo for Branch / Date,Currency,Mapping Not Provided,Mapping Not Provided2,Entity Code,Oracle GL Code,\
Oracle BranchCode,Department Code,Product Code,Channel Code,Intercompany Code,Future_1,Future_2,Amount Debit,Amount Credit,Journal_Reference1,Journal_Reference2,\
Journal_Reference3,Journal_Reference4,Journal_Reference5,Journal_Reference6,Journal_Reference7,Journal_Reference8,Journal_Reference9,Journal_Reference10,Journal_Reference11,\
Journal_Reference12,Journal_Reference13,CreationDate,Column33,Column34,Column35,Column36

query= select  concat(COALESCE(:to_date ,''),'-',COALESCE(br.branch_code,''),'-',COALESCE(br.id,'')) as sl_no, \
'BRNET' as lms,br.id,DATE_FORMAT(:to_date , '%d-%m-%Y') as working_date,ap.currency_code as currency,'','','204' as entity_code,gl.gl_subhead as gl_code, br.micr_code as oracle_branch_code, \
'25' as department_code,'16004' as product_code,'999' as channel_code,'999' as intercompany_code,'999' as future_1,'999' as future_2, \
ifnull(t.amount_debit,0) as amount_debit, ifnull(t.amount_credit,0) as amount_credit, \
lp.account_id,c.customer_id,concat(COALESCE(c.first_name,''),' ',COALESCE(c.middle_name,''),' ',COALESCE(c.last_name,'')) as customer_name,p.product_code, p.product_description,'','','','','','','','', \
date_format(b.current_working_date,'%d-%m-%Y') as business_date,'','','','' \
from account_profiles ap join \
(select e.tenant_code as tenant_code, e.account_id as account_id, \
sum(CASE when account_entry_type = 0 then amount_magnitude else 0 end) as amount_credit, \
sum(CASE when account_entry_type = 1 then amount_magnitude else 0 end) as amount_debit \
from account_entries e, account_profiles p where e.tenant_code = p.tenant_code and e.account_id = p.account_id and p.product_type = 'Loans' and e.transaction_date = :to_date group by e.tenant_code,e.account_id) t \
on t.tenant_code = ap.tenant_code and t.account_id = ap.account_id, \
loan_od_working_registers lw, customers c, loan_od_profiles lp, account_holders ah,\
gl_subheads gl, products p, branches br, banks b \
where lw.tenant_code=ap.tenant_code and c.tenant_code=ap.tenant_code and lp.tenant_code=ap.tenant_code and \
br.tenant_code=ap.tenant_code and ah.tenant_code=ap.tenant_code and gl.tenant_code=ap.tenant_code and b.tenant_code = ap.tenant_code and \
ap.product_code=p.product_code and ap.product_type='Loans' and ap.currency_code = p.currency_code and p.gl_subhead = gl.gl_subhead and \
lw.account_id=ap.account_id and lp.account_id=ap.account_id and ah.customer_id=c.customer_id and ah.account_id=ap.account_id and \
ap.branch_code=br.branch_code and b.tenant_code=:tenant_code and ah.holder_num = 1 \
\
UNION \
\
select  concat(COALESCE(:to_date ,''),'-',COALESCE(br.branch_code,''),'-',COALESCE(br.id,'')) as sl_no, \
'BRNET' as lms,br.id,DATE_FORMAT(:to_date , '%d-%m-%Y') as working_date,ap.currency_code as currency,'','','204' as entity_code,gl.gl_subhead as gl_code, br.micr_code as oracle_branch_code, \
'25' as department_code,'16004' as product_code,'999' as channel_code,'999' as intercompany_code,'999' as future_1,'999' as future_2, \
ifnull(t.amount_debit,0) as amount_debit,ifnull(t.amount_credit,0) as amount_credit, \
ap.account_id,'' as customer_id, '' as customer_name,p.product_code, p.product_description,'','','','','','','','', \
date_format(b.current_working_date,'%d-%m-%Y') as business_date,'','','','' \
from account_profiles ap join \
(select e.tenant_code as tenant_code, e.account_id as account_id,\
   sum(CASE when account_entry_type = 0 then amount_magnitude else 0 end) as amount_credit, \
   sum(CASE when account_entry_type = 1 then amount_magnitude else 0 end) as amount_debit \
from account_entries e, account_profiles p \
 where e.tenant_code = p.tenant_code and e.account_id = p.account_id and p.product_type = 'Internal' and e.transaction_date = :to_date group by e.tenant_code,e.account_id) t \
   on t.tenant_code = ap.tenant_code and t.account_id = ap.account_id, \
gl_subheads gl, products p, branches br, banks b \
where b.tenant_code=ap.tenant_code and gl.tenant_code=ap.tenant_code and br.tenant_code=ap.tenant_code and p.tenant_code = ap.tenant_code and  \
ap.product_type=p.product_type and ap.product_code=p.product_code and p.product_type='Internal' and ap.currency_code = p.currency_code and p.gl_subhead = gl.gl_subhead and gl.gl_head = 'OracleGL' and \
ap.branch_code=br.branch_code and b.tenant_code=:tenant_code

params=tenant_code,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.to_date=Transaction Date
default.to_date=
