header=AccountId,Repayment Type,Value Date:date, Transaction Date:date, User Id, Expected Principal:number, Expected Interest:number, Repaid Principal:number, Repaid Interest:number, Amount:number, Due Principal:number, Due Interest:number 

query=select r.account_id,case when r.repayment_type = 0 then 'ScheduledRepayment' when r.repayment_type = 1 then 'AdvanceRepayment' when r.repayment_type=2 then 'Prepayment' else 'Pre-closure' end,r.value_date,r.transaction_date,r.user_id,\
@prDue:=case when locate('totalPrincipalDue', r.reference) > 0 then substring_index(substring(r.reference,locate ('totalPrincipalDue', r.reference)+18),'|', 1) else 0 end as prDue, \
@intDue:=case when locate('totalNormalInterestDue', r.reference) > 0 then substring_index(substring(r.reference,locate ('totalNormalInterestDue', r.reference)+23),'|', 1) else 0 end as intDue, \
r.principal_magnitude+r.principal_adjustment_magnitude as Principal, (r.normal_interest_magnitude+r.normal_interest_adjustment_magnitude) as NormalInterest, r.amount_magnitude, \
greatest(@prDue-r.principal_magnitude, 0),greatest(@intDue-r.normal_interest_magnitude,0) from loan_od_repayments r where \
tenant_code=:tenant_code and r.transaction_date>=:from_date and r.transaction_date<=:to_date \
UNION \
select r.account_id,case when r.write_off_transaction_type = 2 then 'Full Settlement' when r.write_off_transaction_type = 3 then 'Settlement' when r.write_off_transaction_type=0 then 'WriteOff' end,r.value_date,r.transaction_date,r.user_id,\
@prDue:=case when locate('principalDue', r.reference) > 0 then substring_index(substring(r.reference,locate ('principalDue', r.reference)+13),'|', 1) else 0 end as prDue, \
@intDue:=case when locate('normalInterestDue', r.reference) > 0 then substring_index(substring(r.reference,locate ('normalInterestDue', r.reference)+18),'|', 1) else 0 end as intDue, \
r.principal_magnitude as Principal, (r.normal_interest_magnitude+r.booked_not_due_normal_interest_magnitude) as NormalInterest, r.amount_magnitude, \
greatest(@prDue-r.principal_magnitude, 0),greatest(@intDue-r.normal_interest_magnitude,0) from loan_od_write_offs r where \
tenant_code=:tenant_code and r.transaction_date>=:from_date and r.transaction_date<=:to_date and write_off_transaction_type in (2,3)

params=tenant_code,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
