header=Customer ID,Account Number,Customer Name,Branch Code,Account Name,Open On Date,Loan Amount,Demand No.,Amount,Demand Date,Normal Int,Principal,Penal Int,Balance,Type

query=select ah.customer_id,r.account_id, \
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')),\
p.branch_code,p.account_name,p.opened_on_value_date,l.amount_magnitude,r.demand_num,r.amount_magnitude,r.demand_date,r.normal_interest_magnitude,r.principal_magnitude,r.penal_interest_magnitude,r.balance_magnitude,r.demand_type \
from loan_od_repayment_schedule_items r, account_profiles p, loan_od_profiles l, account_holders ah \
where r.tenant_code = p.tenant_code and r.account_id = p.account_id and r.account_id = :accountId and p.tenant_code = :tenant_code and r.reference = 'Main' \
and l.tenant_code = p.tenant_code and l.account_id = p.account_id and ah.tenant_code = p.tenant_code and ah.account_id = p.account_id and ah.holder_num = 1

params=tenant_code,accountId
label.tenant_code=Tenant Code
default.tenant_code=
label.accountId=Account Id
default.accountId=
