header=AccountId,TransactionName,ValueDate,TransactionDate,ReversalTransactionDate,CreatedAt,Principal,NormalInterest,PenalInterest,Amount,Balance,ReversedPrincipal,TransactionId,ReversalTransactionId,ReversalUserId,CustomerId,BranchCode,ProductCode

query=select ld.account_id,ld.transaction_description,ld.value_date,ld.transaction_date,ld.reversal_transaction_date,ld.created_at,ld.principal_magnitude+ld.principal_adjustment_magnitude, \
ld.normal_interest_magnitude+ ld.normal_interest_adjustment_magnitude, ld.penal_interest_magnitude+ld.penal_interest_adjustment_magnitude, ld.amount_magnitude,ld.balance_magnitude,\
(case when ld.transaction_description='Disbursement' then ld.amount_magnitude else -ld.principal_magnitude-ld.principal_adjustment_magnitude end) as reversed_principal, \
ld.transaction_id,ld.reversal_transaction_id,ld.reversal_user_id,ah.customer_id,ap.branch_code,ap.product_code \
 from loan_od_history_transactions ld ,account_profiles ap,account_holders ah where ld.tenant_code=ap.tenant_code and ap.tenant_code=ah.tenant_code and ap.account_id=ah.account_id \
 and ah.holder_num=1 and ld.account_id=ap.account_id and ap.tenant_code='NBFC1' and \
 ld.transaction_description in ( 'Disbursement', 'Prepayment', 'ScheduledRepayment', 'Pre-closure', 'AdvanceRepayment', 'WriteOff','Settlement', 'Fee Charge', 'Fee Payment') \
 and transaction_date < :from_date and ld.tenant_code=:tenant_code and reversal_transaction_date >= :from_date and reversal_transaction_date <= :to_date

params=tenant_code,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=

