
header=Ac No,Payout Date, Interest, TDS, PAN, Original Ac No,CustomerId, Customer Name, Branch Code, BranchName,Address 1,Address 2,Address 3,City,State,Pin Code,Phone No,Email Id, \
  Open date, Deposit Date, Amount, Maturity Date, Maturity Amount, Tenure, Frequency, Interest Rate, Account Name, Product Code, Tds applicable
 
query= select w.account_id,dp.interest_magnitude, dp.tax_deduction_magnitude,cs.pan,lp.original_account_id,ah.customer_id,\
concat(COALESCE(ah.first_name,''),(case when COALESCE(ah.middle_name,'')='' then '' else (concat(' ',COALESCE(ah.middle_name,''))) end),' ',COALESCE(ah.last_name,'')) as customerName, \
p.branch_code,bc.branch_name, cs.address1,cs.address2,cs.address3,cs.city_code,cs.state_code,cs.pin_code,cs.phone1,cs.email,\
p.opened_on_value_date, w.first_deposit_date,lp.amount_magnitude,w.maturity_date, lp.maturity_amount_magnitude, \
case when \
lp.tenure_unit=1 then lp.tenure_days when lp.tenure_unit=2 then ROUND(lp.tenure_days/7) when \
lp.tenure_unit=3 then ROUND(lp.tenure_days/14) when lp.tenure_unit=4 then lp.tenure_months \
when lp.tenure_unit=5 then ROUND(lp.tenure_months/3) when lp.tenure_unit=6 then ROUND(lp.tenure_months/6) \
when lp.tenure_unit=7 then ROUND(lp.tenure_months/12) end as tenure, \
case when lp.tenure_unit=1 \
then 'DAY' when lp.tenure_unit=2 then 'WEEK' when lp.tenure_unit=3 then 'FORTNIGHT' when \
lp.tenure_unit=4 then 'MONTH' when lp.tenure_unit=5 then 'QUARTER' when lp.tenure_unit=6 \
then 'HALF_YEAR' when lp.tenure_unit=7 then 'YEAR' end as time_unit, \
lp.interest_rate, p.account_name, p.product_code, lp.tax_exempted \
from banks bk,account_balances b,branches bc, \
deposit_payouts dp, deposit_profiles lp,  \
account_holders ah,account_profiles p, deposit_products ps, deposit_working_registers w, \
customers cs left join branches bcs on (bcs.tenant_code = cs.tenant_code and bcs.branch_code = cs.branch_code) \
where ah.holder_num=1 and ah.tenant_code=cs.tenant_code and cs.customer_id=ah.customer_id \
and w.account_id = b.account_id and w.tenant_code = b.tenant_code and dp.account_id = p.account_id and dp.tenant_code = p.tenant_code \
and w.account_id = p.account_id and w.tenant_code = bc.tenant_code \
and p.branch_code=bc.branch_code and p.tenant_code = ps.tenant_code and p.product_code = ps.product_code and p.currency_code = ps.currency_code \
and w.tenant_code = p.tenant_code and lp.tenant_code=p.tenant_code and lp.account_id=p.account_id \
and ah.tenant_code=p.tenant_code and ah.account_id=p.account_id \
and bk.tenant_code = b.tenant_code and w.tenant_code = :tenant_code and dp.value_date >= :from_date and dp.value_date <= :to_date

params=tenant_code,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
