header=GL Head, Product/Account Code,Description,GL Subhead,GL Code,Branch Code,Branch Name,Category,Product Type,Department,Opening Balance,Debit Amount,Credit Amount,Closing Balance

query=select gl.gl_head, pr.product_code, pr.product_description, pr.gl_subhead, pr.gl_code, ap.branch_code,'All' as branch_name,pr.category, e.reference2,e.reference3, \
sum(case when account_entry_type = 1 and e.value_date < :from_date  then -amount_magnitude when account_entry_type = 0 and e.value_date < :from_date  then amount_magnitude else 0 end) as opening_balance, \
sum(CASE when account_entry_type = 1 and e.value_date >= :from_date  and e.value_date <= :to_date  then amount_magnitude else 0 end) as debit_transactions, \
sum(CASE when account_entry_type = 0 and e.value_date >= :from_date  and e.value_date <= :to_date  then amount_magnitude else 0 end) as credit_transactions, \
sum(case when account_entry_type = 1 and e.value_date <= :to_date  then -amount_magnitude when account_entry_type = 0 and e.value_date <= :to_date  then amount_magnitude else 0 end) as closing_balance \
from account_entries e, account_profiles ap, products pr,gl_subheads gl,branchset_branches bs,branches  b \
where e.tenant_code = ap.tenant_code and e.account_id = ap.account_id and  ap.gl_subhead = gl.gl_subhead and ap.branch_code=bs.branch_code and ap.product_type = pr.product_type and  \
ap.tenant_code = pr.tenant_code and ap.product_code=pr.product_code and ap.currency_code=pr.currency_code and b.branch_code=bs.branch_code and bs.branch_code=ap.branch_code and \
(:reference2_select is null or (e.reference2=pr.reference2 and e.reference2=:reference2_select)) and (:reference3_select is null or (e.reference3=pr.reference3 and e.reference3=:reference3_select )) and \
e.tenant_code =:tenant_code and bs.branchset_code = :branchset_code_select group by gl.gl_head,pr.tenant_code,pr.gl_code

params=tenant_code,branchset_code_select,reference2_select,reference3_select,from_date,to_date
label.tenant_code=Tenant Code
default.tenant_code=
label.branchset_code_select=Branchset
default.branchset_code_select=
label.reference2_select=Product Type
label.reference3_select=Department
label.from_date=From Date
default.from_date=
label.to_date=To Date
default.to_date=
