reminderAlerts=repaym5,repaym3,repaym1,disburse1,advanceRepaymentSchedule,repayrm6
Repayment=
Disbursement=
DisbursementConfirmation=disbursem3
otp=otp
branchAlerts=demandsOverdue

languages=English,Tamil,Telugu
states.Telugu=
states.Tamil=
states.English=GJ,MP,AP,TN

repaym5.message.English=Dear Customer, Your repayment amount INR {4} is due this month, please ensure to deposit the same before due date {6} to avoid penalty charges.
repaym5.query=select bc.state_code,c.phone1,c.email,c.first_name,w.installment_amount_magnitude+w.interest_adjustment_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),h.customer_id,p.product_code \
from account_profiles p, banks b, account_holders h, loan_od_profiles l, loan_od_working_registers w, customers c,branches bc \
where h.tenant_code = :tenantCode and h.tenant_code = b.tenant_code and h.tenant_code = p.tenant_code and h.account_id = p.account_id and \
l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and h.customer_id = c.customer_id and \
h.tenant_code = bc.tenant_code and h.tenant_code = c.tenant_code and p.branch_code=bc.branch_code and w.installment_amount_magnitude is not null and \
date_add(b.current_working_date, INTERVAL 6 DAY) = w.next_demand_run_date and p.operational_status=0 and w.maturity_date>b.current_working_date
repaym5.scripts=InstallmentAmount.groovy

repaym3.message.English=Dear Customer, Your repayment amount INR {4} is due this month, please ensure to deposit the same before due date {6} to avoid penalty charges.
repaym3.query=select bc.state_code,c.phone1,c.email,c.first_name,w.installment_amount_magnitude+w.interest_adjustment_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),h.customer_id,p.product_code \
from account_profiles p, banks b, account_holders h, loan_od_profiles l, loan_od_working_registers w, customers c,branches bc \
where h.tenant_code = :tenantCode and h.tenant_code = b.tenant_code and h.tenant_code = p.tenant_code and h.account_id = p.account_id and \
l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and h.customer_id = c.customer_id and \
h.tenant_code = bc.tenant_code and h.tenant_code = c.tenant_code and p.branch_code=bc.branch_code and w.installment_amount_magnitude is not null and \
date_add(b.current_working_date, INTERVAL 4 DAY) = w.next_demand_run_date and p.operational_status=0 and w.maturity_date>b.current_working_date

repaym1.message.English={3} EMI amount INR {4} due on {7} for loan account {5}. Please maintain sufficient balance in your bank account on due date.
repaym1.query=select bc.state_code,c.phone1,c.email,c.first_name,w.installment_amount_magnitude+w.interest_adjustment_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),h.customer_id,p.product_code \
from account_profiles p, banks b, account_holders h, loan_od_profiles l, loan_od_working_registers w, customers c,branches bc \
where h.tenant_code = :tenantCode and h.tenant_code = b.tenant_code and h.tenant_code = p.tenant_code and h.account_id = p.account_id and \
l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and h.customer_id = c.customer_id and \
h.tenant_code = bc.tenant_code and h.tenant_code = c.tenant_code and p.branch_code=bc.branch_code and w.installment_amount_magnitude is not null and \
date_add(b.current_working_date, INTERVAL 2 DAY) = w.next_demand_run_date and p.operational_status=0 and w.maturity_date>b.current_working_date

repayp1.message.English=Dear Customer, We have received the payment of INR {4} for your loan account {5}. Next repayment date {7}
repayp1.query=select bc.state_code,concat(c.phone1,',',u.phone1),c.email,c.first_name,s.amount_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),h.customer_id,p.product_code,date_format(s.transaction_date, '%d/%m/%Y'),s.repayment_num, -b.balance_magnitude \
from account_profiles p, account_holders h, loan_od_profiles l, loan_od_working_registers w, loan_od_repayments s, customers c,branches bc, users u, account_balances b \
where h.tenant_code = :tenantCode and h.tenant_code = bc.tenant_code and h.tenant_code = p.tenant_code and p.tenant_code = b.tenant_code and h.account_id = p.account_id \
and p.account_id = b.account_id and l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and \
s.tenant_code = h.tenant_code and s.account_id = h.account_id and p.tenant_code=u.tenant_code and c.tenant_code = p.tenant_code and \
c.customer_id = h.customer_id and p.branch_code=bc.branch_code and p.open_user_id=u.userid and h.account_id = :accountId and s.repayment_num = :sequenceNum

repayrm6.message.English=Dear RM, Your Client's {3} {7} repayment amount INR {4} is due this month on due date {6}
repayrm6.query=select bc.state_code,c.phone1,c.email,c.first_name,(-bl.balance_magnitude+w.interest_adjustment_magnitude),p.account_id,\
date_format(DATE_ADD(w.first_disbursement_date, INTERVAL l.moratorium_period_days DAY), '%d/%m/%Y'),h.customer_id,p.product_code \
from account_profiles p, banks b, account_holders h, loan_od_profiles l, loan_od_working_registers w, customers c,branches bc,account_balances bl, loan_od_products lp \
where h.tenant_code = :tenantCode and p.tenant_code=b.tenant_code and b.tenant_code=h.tenant_code and h.tenant_code=l.tenant_code and l.tenant_code=w.tenant_code and \
w.tenant_code=c.tenant_code and c.tenant_code=bc.tenant_code and bc.tenant_code=bl.tenant_code and bl.tenant_code=lp.tenant_code and p.account_id=l.account_id \
and l.account_id=h.account_id and l.account_id=w.account_id and l.account_id=bl.account_id and p.product_code=lp.product_code and p.branch_code=bc.branch_code \
and h.customer_id=c.customer_id  and lp.repayment_method=0 and lp.moratorium_type=1 and l.moratorium_period_unit=1 and \
DATE_ADD(b.current_working_date, INTERVAL 2 DAY) = (DATE_ADD(w.first_disbursement_date, INTERVAL l.moratorium_period_days DAY)) and \
p.operational_status=0 and w.maturity_date>b.current_working_date

advanceRepaymentSchedule.query=select b.state_code,concat(h.phone1,',',h.phone1),concat(h.email,',',c.relationship_manager_email_id),'' as firstName,'' as amount,w.account_id from \
loan_od_working_registers w,banks b, account_holders h, account_profiles p, customers c \
where h.tenant_code = :tenantCode and h.tenant_code=c.tenant_code and b.tenant_code=w.tenant_code and b.tenant_code=h.tenant_code and p.tenant_code = h.tenant_code and \
h.customer_id=c.customer_id and h.holder_num=1 and w.account_id=h.account_id and p.account_id = h.account_id and \
date_add(b.current_working_date, INTERVAL 3 DAY) = w.next_demand_run_date and p.operational_status = 0
advanceRepaymentSchedule.emailSubject=Repayment Schedule
advanceRepaymentSchedule.emailBody=<br/><br/>Please find attached Repayment Schedule for AccountId : {5}
advanceRepaymentSchedule.reportNames=RepaymentSchedule(accountId_text:5)

otp.query=select b.state_code, u.phone1, o.one_time_password, o.id, u.emailid, u.userid, u.name, u.phone2 from users u, banks b, otp o where u.otp_auth_applicable=1 and u.tenant_code=:tenantCode and u.userid=:userId and o.id=:otpId and o.userid=u.userid and b.tenant_code=u.tenant_code
otp.message.English={2} is the OTP to login to your account in Encore LMS. This code will be valid for 10 min.

disburse1.message.English=Dear Customer, Your Disbursement request has been processed and Account {5} for a sum of INR {4} is disbursed, loan amount will be reflected into your registered Bank account in another 2-3 working hours.
disburse1.query=select bc.state_code,concat(c.phone1,',',u.phone1),c.email,c.first_name,d.amount_magnitude,p.account_id,date_format(d.transaction_date,'%d/%m/%Y') \
from account_profiles p,banks b,account_holders h,loan_od_profiles l,loan_od_disbursements d,customers c,branches bc, users u where \
h.tenant_code=:tenantCode and h.tenant_code=bc.tenant_code and h.tenant_code=b.tenant_code and h.tenant_code=p.tenant_code and h.account_id=p.account_id \
and l.tenant_code=h.tenant_code and p.tenant_code=u.tenant_code and l.account_id=h.account_id and d.tenant_code=h.tenant_code and d.account_id=h.account_id and h.tenant_code=c.tenant_code and \
h.customer_id=c.customer_id and d.tenant_code=h.tenant_code and d.account_id=h.account_id and p.branch_code=bc.branch_code and p.open_user_id=u.userid and \
date_sub(b.current_working_date, INTERVAL 1 DAY) = d.transaction_date and p.operational_status = 0

disbursem2.emailSubject=Repayment Schedules & Disbursement Receipt
disbursem2.emailBody=<br/><br/>Please find attached Repayment Schedule and Disbursement Receipt for AccountId : 
disbursem2.reportNames=DisbursementReceipt(transactionId_text:10),RepaymentSchedule(accountId_text:5)
disbursem2.query=select bc.state_code,concat_ws(',',c.phone1,u.phone1),concat_ws(",",h.email,c.relationship_manager_email_id),c.first_name,s.amount_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),date_format(s.transaction_date, '%d/%m/%Y'),s.sequence_num, -b.balance_magnitude,s.transaction_id \
from account_profiles p, account_holders h, loan_od_profiles l, loan_od_working_registers w, loan_od_disbursements s, customers c,branches bc, users u, account_balances b \
where h.tenant_code = :tenantCode and h.tenant_code = bc.tenant_code and h.tenant_code = p.tenant_code and p.tenant_code = b.tenant_code and h.account_id = p.account_id and \
p.account_id = b.account_id and l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and s.tenant_code = h.tenant_code and \
s.account_id = h.account_id and p.tenant_code=u.tenant_code and c.tenant_code = p.tenant_code and \
c.customer_id = h.customer_id and p.branch_code=bc.branch_code and p.open_user_id=u.userid and h.account_id = :accountId and s.sequence_num = :sequenceNum
disbursem2.message.English=Dear Customer, Your Disbursement request has been processed and Account {5} for a sum of INR {4} is disbursed, loan amount will be reflected into your registered Bank account in another 2-3 working hours.

disbursem3.query=select bc.state_code,u.phone1,c.relationship_manager_email_id,c.first_name,s.net_disbursement_magnitude,p.account_id,\
date_format(w.next_demand_run_date, '%d/%m/%Y'),date_format(s.transaction_date, '%d/%m/%Y'),s.sequence_num, -b.balance_magnitude,s.transaction_id,substring_index(reference, '|', 1) \
from account_profiles p, account_holders h, loan_od_profiles l, loan_od_working_registers w, loan_od_disbursements s, customers c,branches bc, users u, account_balances b \
where h.tenant_code = :tenantCode and h.tenant_code = bc.tenant_code and h.tenant_code = p.tenant_code and p.tenant_code = b.tenant_code and h.account_id = p.account_id \
and p.account_id = b.account_id and l.tenant_code = h.tenant_code and l.account_id = h.account_id and w.tenant_code = h.tenant_code and w.account_id = h.account_id and \
s.tenant_code = h.tenant_code and s.account_id = h.account_id and p.tenant_code=u.tenant_code and c.tenant_code = p.tenant_code and \
c.customer_id = h.customer_id and p.branch_code=bc.branch_code and p.open_user_id=u.userid and h.account_id = :accountId and s.sequence_num = :sequenceNum and reference regexp 'UTR:'
disbursem3.message.English=Disbursement amount of INR {4} for account {5} of customer {3} has been credited: {11}

demandsOverdue.userRoles=Report
demandsOverdue.reportNames=DemandOverdueReport
