#-------------------------------------------------------------------------------
# MySQL Settings

jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://10.0.1.5:3306/encoredb?autoReconnect=true&useSSL=false
jdbc.username=root
jdbc.password=mysql-Password
jdbc.initialSize=20
jdbc.minimumIdleConnections=10
jdbc.maximumIdleConnections=20
jdbc.maximumActiveConnections=100
jdbc.maxWait = 10000

#Properties that control the population of schema and data for a new data source
#jdbc.initLocation=classpath:db/mysql/initDB.sql
#jdbc.dataLocation=classpath:db/mysql/populateDB.sql

# Property that determines which JPA DatabasePlatform to use with TopLink Essentials
jpa.databasePlatform=oracle.toplink.essentials.platform.database.MySQL4Platform
# Property that determines which database to use with an AbstractJpaVendorAdapter
jpa.database=MYSQL
jpa.showSql=true
jasperVirtualizer.maxSize=50

# Database dump parameters
db.user=root
db.password=ENC(OwRE4O7lYT2oMONu8CREetFqaueoox9c)
db.dumptimeout=180
db.dumpScriptFile=/opt/bin/mysql_dump.sh
accountDumpScriptFile=/opt/bin/dumpAccount.sh
ssh.port=22

#-------------------------------------------------------------------------------
# HSQL Settings

#jdbc.driverClassName=org.hsqldb.jdbcDriver
#jdbc.url=jdbc:hsqldb:mem:encoredb
#jdbc.username=sa
#jdbc.password=

# Properties that control the population of schema and data for a new data source
#jdbc.initLocation=classpath:db/hsqldb/initDB.sql
#jdbc.dataLocation=classpath:db/hsqldb/populateDB.sql

# Property that determines which JPA DatabasePlatform to use with TopLink Essentials
#jpa.databasePlatform=org.springframework.samples.petclinic.toplink.EssentialsHSQLPlatformWithNativeSequence

# Property that determines which database to use with an AbstractJpaVendorAdapter
#jpa.database=HSQL

