#-------------------------------------------------------------------------------
# Kafka Settings
spring.kafka.enabled=true
spring.kafka.listener.concurrency=3

spring.kafka.consumer.bootstrapServers=localhost:9092
spring.kafka.consumer.groupId=group_id
spring.kafka.consumer.autoOffsetReset=earliest
spring.kafka.consumer.enableAutoCommit=false
spring.kafka.consumer.keyDeserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.valueDeserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.bootstrapServers=localhost:9092
spring.kafka.producer.keySerializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.valueSerializer=org.springframework.kafka.support.serializer.JsonSerializer


