
batch.gridsize=4
batch.commitInterval=50
batch.skipLimit=10
report.dbInsert.gridsize=8
report.dbInsert.commitInterval=1
report.commitInterval=100
report.gridsize=4

tenants.reloadFrequency=100000

siteName=NBFC1
mail.from=noreply@sen-sei.in
mail.smtp.auth=true
mail.smtp.starttls.enable=false
mail.smtp.host=smtp.gmail.com
mail.transport.protocol=smtp
#mail.smtp.port=587
mail.smtp.port=465
mail.smtp.user=noreply@sen-sei.in
mail.smtp.password=password@123
mail.smtp.ssl.enable=true
mail.smtp.socketFactory.port=465
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.smtp.ssl.protocols=TLSv1.2

dev.digio.ach.corporateConfigId=PPPPPP
dev.digio.ach.clientId=QQQQQ
dev.digio.ach.clientSecret=RRRRRR
dev.digio.ach.url=https://ext.digio.in:444
prod.digio.ach.corporateConfigId=CCCCCCC
prod.digio.ach.clientId=DDDDDDD
prod.digio.ach.clientSecret=EEEEEEEEE
prod.digio.ach.url=https://api.digio.in

#comma separated whitelist of IP addresses
webhook.whitelist=0.0.0.0

encoreUri:NA
encoreUserId:NA
encorePassword:NA
