tenants=MG
pattern.MG=encore
eodJob.cronString.MG=0 30 21 * * ? *
alertJob.cronString.MG=0 0/30 * * * ? *

numJobTriggers.MG=2
Job1.cronString.MG=0 0 0 1 1 ? 2099
Job2.cronString.MG=0 0 0 1 1 ? 2099

logAPIUsage.enable.MG=true
logAPIUsage.ignore.MG=png,jpg,js,ico,css
logAPIUsage.logResponseContentTypes.MG=application/json,text/html
logAPIUsage.responseMaxLength.MG=5000