INSERT INTO anchor_rating_templates (id, name, version, active, config_json, created_at, updated_at)
VALUES (
    'a1000000-0000-4000-8000-000000000001',
    'Default anchor rating checklist',
    1,
    TRUE,
    '{"questions":[{"key":"externalCreditRating","label":"External credit rating (if available)","hint":"Objective — agency rating or not rated.","options":[{"value":"AAA","label":"AAA","score":17},{"value":"AA","label":"AA","score":17},{"value":"A","label":"A","score":15},{"value":"BBB","label":"BBB","score":12},{"value":"BB","label":"BB","score":8},{"value":"B","label":"B","score":5},{"value":"C","label":"C / below investment grade","score":0},{"value":"D","label":"D / default","score":0},{"value":"NOT_RATED","label":"Not rated externally","score":6}]},{"key":"financialPerformance","label":"Financial performance (reviewed financials)","options":[{"value":"STRONG","label":"Strong — stable revenue and margins","score":15},{"value":"SATISFACTORY","label":"Satisfactory","score":10},{"value":"WEAK","label":"Weak — declining or volatile","score":4},{"value":"DISTRESSED","label":"Distressed","score":0}]},{"key":"businessVintage","label":"Business vintage","options":[{"value":"GTE_10","label":"10+ years","score":12},{"value":"Y5_9","label":"5–9 years","score":9},{"value":"Y3_4","label":"3–4 years","score":5},{"value":"LT_3","label":"Under 3 years","score":0}]},{"key":"gstCompliance","label":"GST / statutory compliance","options":[{"value":"FULL","label":"Fully compliant","score":12},{"value":"MINOR_DELAYS","label":"Minor filing delays","score":7},{"value":"SIGNIFICANT_GAPS","label":"Significant gaps","score":0}]},{"key":"industryRisk","label":"Industry / sector risk","options":[{"value":"LOW","label":"Low","score":10},{"value":"MEDIUM","label":"Medium","score":6},{"value":"HIGH","label":"High","score":2}]},{"key":"adverseNewsFlow","label":"Adverse news flow","hint":"Subjective — media, regulatory, or market signals.","options":[{"value":"NONE","label":"None identified","score":12},{"value":"MINOR","label":"Minor / isolated","score":6},{"value":"MATERIAL","label":"Material adverse news","score":0}]},{"key":"legalLitigation","label":"Legal / litigation history","options":[{"value":"NONE","label":"None","score":10},{"value":"RESOLVED","label":"Resolved matters only","score":6},{"value":"ONGOING_MATERIAL","label":"Ongoing material litigation","score":0}]},{"key":"managementTrackRecord","label":"Management track record","options":[{"value":"STRONG","label":"Strong — proven leadership","score":12},{"value":"ADEQUATE","label":"Adequate","score":8},{"value":"CONCERNS","label":"Concerns identified","score":2}]}],"ratingBands":[{"rating":"A","minScore":80,"maxScore":100,"label":"A — Strong"},{"rating":"B","minScore":65,"maxScore":79,"label":"B — Satisfactory"},{"rating":"C","minScore":50,"maxScore":64,"label":"C — Refer / manual review"},{"rating":"D","minScore":0,"maxScore":49,"label":"D — Not acceptable"}]}'::jsonb,
    now(),
    now()
);
